# Generated by AI - Python Module

"""
Example usage of MultidimensionalPaint module.

This file demonstrates various features of the module including:
- Point creation and management
- Shape drawing
- Point selection
- Data analysis and export
"""

from multidimention_paint import MultidimensionalPaint, Point, PointSet
import math


def example_1_basic_operations():
    """Example 1: Basic point and shape operations."""
    print("\n" + "="*60)
    print("Example 1: Basic Operations")
    print("="*60)

    painter = MultidimensionalPaint()

    # Add points in 2D
    painter.add_point(0, 0)
    painter.add_point(5, 5)
    painter.add_point(10, 10)
    painter.add_point(7, 3)

    print(f"Total points: {painter.get_point_count()}")
    print(f"All points: {painter.get_all_points()}")

    # Draw some shapes
    painter.draw_line((0, 0), (10, 10))
    painter.draw_circle((5, 5), 3)
    painter.draw_rectangle((0, 0), (10, 10))

    print(f"Total shapes: {painter.get_shape_count()}")


def example_2_3d_points():
    """Example 2: Working with 3D points."""
    print("\n" + "="*60)
    print("Example 2: Working with 3D Points")
    print("="*60)

    painter = MultidimensionalPaint()

    # Add 3D points
    painter.add_point(0, 0, 0, label="origin")
    painter.add_point(1, 2, 3, label="point_a")
    painter.add_point(4, 5, 6, label="point_b")
    painter.add_point(10, 10, 10, label="far_point")

    # Get a specific point
    origin = painter.get_point_by_label("origin")
    print(f"Origin: {origin}")

    # Calculate distance
    point_a = painter.get_point_by_label("point_a")
    distance = origin.distance_to(point_a)
    print(f"Distance from origin to point_a: {distance:.2f}")

    # Draw 3D circle
    painter.draw_circle((5, 5, 5), 3)
    print(f"Added 3D circle")


def example_3_point_selection():
    """Example 3: Point selection operations."""
    print("\n" + "="*60)
    print("Example 3: Point Selection")
    print("="*60)

    painter = MultidimensionalPaint()

    # Create a grid of points
    for x in range(0, 11, 2):
        for y in range(0, 11, 2):
            painter.add_point(float(x), float(y))

    print(f"Total points created: {painter.get_point_count()}")

    # Selection 1: Single point
    selected = painter.select_single_point((4, 4), tolerance=0.5)
    print(f"Single point selection: {len(selected)} points")

    # Selection 2: Line selection
    selected = painter.select_line((0, 0), (10, 10), tolerance=1.0)
    print(f"Line selection: {len(selected)} points")

    # Selection 3: Region selection
    selected = painter.select_within_region((0, 0), (5, 5))
    print(f"Region selection (0,0) to (5,5): {len(selected)} points")

    # Selection 4: Nearest points
    selected = painter.select_nearest((5, 5), count=5)
    print(f"5 nearest points to (5,5): {selected}")

    # Selection 5: All points
    selected = painter.select_all()
    print(f"Total points selected: {len(selected)}")


def example_4_shape_selection():
    """Example 4: Selection within shapes."""
    print("\n" + "="*60)
    print("Example 4: Selection Within Shapes")
    print("="*60)

    painter = MultidimensionalPaint()

    # Create random-like points
    points_coords = [
        (2, 2), (3, 3), (4, 4), (5, 5), (6, 6),
        (1, 5), (5, 1), (9, 9), (1, 1), (9, 1),
        (1, 9), (9, 5), (5, 9), (7, 7), (3, 7)
    ]

    painter.add_points_from_list(points_coords)

    # Draw a circle
    circle = painter.draw_circle((5, 5), 4, filled=True)
    selected = painter.select_within_shape(circle)
    print(f"Points within circle: {len(selected)} points")

    # Draw a rectangle
    rect = painter.draw_rectangle((2, 2), (8, 8), filled=True)
    selected = painter.select_within_shape(rect)
    print(f"Points within rectangle: {len(selected)} points")


def example_5_all_shapes():
    """Example 5: Drawing all types of shapes."""
    print("\n" + "="*60)
    print("Example 5: All Shape Types")
    print("="*60)

    painter = MultidimensionalPaint()

    # Add center reference point
    painter.add_point(10, 10, label="center")

    # Line
    painter.draw_line((5, 5), (15, 15), filled=False)
    print("✓ Line drawn")

    # Circle
    painter.draw_circle((10, 10), 5, filled=True)
    print("✓ Circle drawn")

    # Rectangle
    painter.draw_rectangle((8, 8), (12, 12), filled=False)
    print("✓ Rectangle drawn")

    # Square
    painter.draw_square((20, 20), 10, filled=True)
    print("✓ Square drawn")

    # Ellipse
    painter.draw_ellipse((30, 30), 8, 5, rotation=math.pi/4)
    print("✓ Ellipse drawn")

    # Arc
    painter.draw_arc((40, 40), 5, 0, math.pi/2)
    print("✓ Arc drawn")

    # Closed shape (polygon)
    vertices = [(50, 45), (55, 45), (57, 50), (55, 55), (50, 55), (48, 50)]
    painter.draw_closed_shape(vertices)
    print("✓ Closed shape drawn")

    print(f"\nTotal shapes: {painter.get_shape_count()}")


def example_6_analysis():
    """Example 6: Point analysis and statistics."""
    print("\n" + "="*60)
    print("Example 6: Analysis and Statistics")
    print("="*60)

    painter = MultidimensionalPaint()

    # Add points
    for i in range(1, 6):
        for j in range(1, 6):
            painter.add_point(float(i*2), float(j*2))

    # Get statistics
    stats = painter.get_statistics()
    print(f"Point count: {stats['point_count']}")
    print(f"Shape count: {stats['shape_count']}")
    print(f"Dimensions: {stats['dimensions']}")
    print(f"Bounding box: {stats['bounding_box']}")
    print(f"Centroid: {stats['centroid']}")

    # Find nearest/farthest
    nearest = painter.find_nearest_point((5, 5))
    farthest = painter.find_farthest_point((5, 5))
    print(f"Nearest to (5,5): {nearest}")
    print(f"Farthest from (5,5): {farthest}")


def example_7_metadata():
    """Example 7: Working with point metadata."""
    print("\n" + "="*60)
    print("Example 7: Point Metadata")
    print("="*60)

    painter = MultidimensionalPaint()

    # Add points with metadata
    p1 = painter.add_point(0, 0, label="point1")
    p1.set_metadata("color", "red")
    p1.set_metadata("layer", 1)
    p1.set_metadata("visible", True)

    p2 = painter.add_point(5, 5, label="point2")
    p2.set_metadata("color", "blue")
    p2.set_metadata("layer", 2)
    p2.set_metadata("visible", False)

    # Export and display
    exported = painter.export_points()
    for i, point in enumerate(exported):
        print(f"\nPoint {i+1}:")
        print(f"  Coordinates: {point['coords']}")
        print(f"  Label: {point['label']}")
        print(f"  Metadata: {point['metadata']}")


def example_8_selection_history():
    """Example 8: Selection history management."""
    print("\n" + "="*60)
    print("Example 8: Selection History")
    print("="*60)

    painter = MultidimensionalPaint()

    # Create points
    for i in range(10):
        painter.add_point(float(i), float(i))

    # First selection
    painter.select_all()
    painter.save_selection()
    print(f"Selection 1 saved: {painter.get_selection_count()} points")

    # Second selection
    painter.clear_selection()
    painter.select_nearest((5, 5), count=3)
    painter.save_selection()
    print(f"Selection 2 saved: {painter.get_selection_count()} points")

    # Load first selection
    painter.load_selection(0)
    print(f"Loaded selection 1: {painter.get_selection_count()} points")

    # Load second selection
    painter.load_selection(1)
    print(f"Loaded selection 2: {painter.get_selection_count()} points")


def example_9_high_dimensional():
    """Example 9: Working with high-dimensional points."""
    print("\n" + "="*60)
    print("Example 9: High-Dimensional Points")
    print("="*60)

    painter = MultidimensionalPaint()

    # 4D points
    painter.add_point(0, 0, 0, 0, label="4d_origin")
    painter.add_point(1, 2, 3, 4, label="4d_point")
    print(f"✓ 4D points created")

    # 5D points
    painter.add_point(1, 2, 3, 4, 5, label="5d_point")
    print(f"✓ 5D point created")

    # 10D points
    coords = tuple(float(i) for i in range(10))
    painter.add_point(*coords, label="10d_point")
    print(f"✓ 10D point created")

    # Statistics
    stats = painter.get_statistics()
    print(f"Points: {stats['point_count']}")
    print(f"Dimensions: {stats['dimensions']}")


def example_10_data_export():
    """Example 10: Exporting data."""
    print("\n" + "="*60)
    print("Example 10: Data Export")
    print("="*60)

    painter = MultidimensionalPaint()

    # Add points with labels
    painter.add_point(1, 2, label="A")
    painter.add_point(3, 4, label="B")
    painter.add_point(5, 6, label="C")

    # Add shapes
    painter.draw_circle((5, 5), 3, filled=True)
    painter.draw_rectangle((1, 1), (9, 9), filled=False)

    # Export points
    print("\nExported Points:")
    points_data = painter.export_points()
    for point in points_data:
        print(f"  {point['label']}: {point['coords']}")

    # Export shapes
    print("\nExported Shapes:")
    shapes_data = painter.export_shapes()
    for i, shape in enumerate(shapes_data):
        print(f"  Shape {i+1}: {shape['type']} "
              f"(filled={shape['filled']}, "
              f"points={len(shape['points'])})")


def main():
    """Run all examples."""
    print("\n" + "#"*60)
    print("# MultidimensionalPaint Module Examples")
    print("#"*60)

    example_1_basic_operations()
    example_2_3d_points()
    example_3_point_selection()
    example_4_shape_selection()
    example_5_all_shapes()
    example_6_analysis()
    example_7_metadata()
    example_8_selection_history()
    example_9_high_dimensional()
    example_10_data_export()

    print("\n" + "#"*60)
    print("# All examples completed!")
    print("#"*60 + "\n")


if __name__ == "__main__":
    main()
