# Generated by AI - Python Module

"""
PydocsExport - Module d'exportation de documentation Python
============================================================

Ce module permet d'exporter la documentation complète de Python
en plusieurs formats: TXT, PDF, EPUB, MOBI, HTML.

Author: Copilot
Version: 1.0.0
"""

from .exporter import PydocsExporter
from .formatter import TextFormatter, PDFFormatter, EbookFormatter
from .index_manager import IndexManager

__version__ = "1.0.0"
__all__ = [
    "PydocsExporter",
    "TextFormatter",
    "PDFFormatter",
    "EbookFormatter",
    "IndexManager",
]
