@REM Generated by AI - Utility Batch Script for Windows

@echo off
setlocal enabledelayedexpansion

:menu
cls
echo ============================================================
echo      M13 Collection - Command Center
echo ============================================================
echo.
echo [1] Run All Tests (pytest)
echo [2] Run Tests with Verbose Output
echo [3] Run Tests with Coverage Report
echo [4] Run GUI Menu (Main)
echo [5] Run GUI Menu (Utilities)
echo [6] Run GUI Menu (VariableExtender)
echo [7] Run Console Menu
echo [8] Run Specific Module Tests
echo [9] Format Code (black)
echo [10] Check Code Style (flake8)
echo [11] Show Test Collection
echo [12] Run GenericTree Tests Only
echo [13] Run MenuMaker Tests Only
echo [14] Run MultiTable Tests Only
echo [15] Exit
echo.
set /p choice="Select option (1-15): "

if "%choice%"=="1" goto run_tests
if "%choice%"=="2" goto run_tests_verbose
if "%choice%"=="3" goto run_tests_coverage
if "%choice%"=="4" goto run_main_gui
if "%choice%"=="5" goto run_utilities_gui
if "%choice%"=="6" goto run_variableextender_gui
if "%choice%"=="7" goto run_console_menu
if "%choice%"=="8" goto run_specific_tests
if "%choice%"=="9" goto format_code
if "%choice%"=="10" goto check_style
if "%choice%"=="11" goto show_collection
if "%choice%"=="12" goto run_generictree_tests
if "%choice%"=="13" goto run_menumaker_tests
if "%choice%"=="14" goto run_multitable_tests
if "%choice%"=="15" goto exit

echo Invalid choice. Please try again.
timeout /t 2 /nobreak
goto menu

:run_tests
echo.
echo Running all tests...
pytest
pause
goto menu

:run_tests_verbose
echo.
echo Running tests with verbose output...
pytest -v
pause
goto menu

:run_tests_coverage
echo.
echo Running tests with coverage report...
pytest --cov=Utilities --cov=VariableExtender --cov-report=html
echo.
echo Coverage report generated in htmlcov/index.html
pause
goto menu

:run_main_gui
echo.
echo Launching main GUI menu...
python run_gui.py
goto menu

:run_utilities_gui
echo.
echo Launching Utilities GUI menu...
python Utilities/run_gui.py
goto menu

:run_variableextender_gui
echo.
echo Launching VariableExtender GUI menu...
python VariableExtender/run_gui.py
goto menu

:run_console_menu
echo.
echo Launching console menu...
python run.py
goto menu

:run_specific_tests
echo.
echo Available test modules:
echo [1] GenericTree (VariableExtender/generic_tree/test_generic_tree_complete.py)
echo [2] MenuMaker (VariableExtender/MenuMaker/test_menumaker_complete.py)
echo [3] MultiTable (VariableExtender/Multidimention_table/test_multitable_complete.py)
echo.
set /p module="Select module (1-3): "

if "%module%"=="1" (
    pytest VariableExtender/generic_tree/test_generic_tree_complete.py -v
) else if "%module%"=="2" (
    pytest VariableExtender/MenuMaker/test_menumaker_complete.py -v
) else if "%module%"=="3" (
    pytest VariableExtender/Multidimention_table/test_multitable_complete.py -v
) else (
    echo Invalid selection
)
pause
goto menu

:format_code
echo.
echo Formatting code with black...
black Utilities VariableExtender --line-length 100
echo.
echo Code formatting complete!
pause
goto menu

:check_style
echo.
echo Checking code style with flake8...
flake8 Utilities VariableExtender --max-line-length=100 --ignore=E203,W503
echo.
echo Style check complete!
pause
goto menu

:show_collection
echo.
echo Collecting tests...
pytest --collect-only
pause
goto menu

:run_generictree_tests
echo.
echo Running GenericTree tests...
pytest VariableExtender/generic_tree/test_generic_tree_complete.py -v
pause
goto menu

:run_menumaker_tests
echo.
echo Running MenuMaker tests...
pytest VariableExtender/MenuMaker/test_menumaker_complete.py -v
pause
goto menu

:run_multitable_tests
echo.
echo Running MultiTable tests...
pytest VariableExtender/Multidimention_table/test_multitable_complete.py -v
pause
goto menu

:exit
echo.
echo Goodbye!
exit /b 0
