# Generated by AI - GUI Menu Generator using Tkinter

"""Generate run_gui.py files with tkinter interface for all modules."""

import os

# Main GUI
main_gui = '''# Generated by AI - Main GUI Menu
"""
M13 Python Modules Collection - GUI Menu

Interactive graphical menu using tkinter to select and run modules.
"""

import tkinter as tk
from tkinter import ttk, messagebox
import subprocess
import sys
from pathlib import Path


class MainGUIMenu:
    """Main menu GUI using tkinter."""
    
    def __init__(self, root):
        """Initialize main GUI menu."""
        self.root = root
        self.root.title("M13 Python Modules Collection")
        self.root.geometry("600x400")
        self.root.resizable(False, False)
        
        # Center window
        self.center_window()
        
        # Create main frame
        main_frame = ttk.Frame(root, padding="20")
        main_frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        
        # Title
        title = ttk.Label(main_frame, text="M13 Python Modules Collection", 
                         font=("Arial", 16, "bold"))
        title.grid(row=0, column=0, columnspan=2, pady=10)
        
        # Subtitle
        subtitle = ttk.Label(main_frame, text="Select a module category",
                            font=("Arial", 10))
        subtitle.grid(row=1, column=0, columnspan=2, pady=5)
        
        # Buttons
        ttk.Button(main_frame, text="Utilities Modules", 
                  command=self.open_utilities).grid(row=2, column=0, padx=5, pady=10, sticky="ew")
        ttk.Button(main_frame, text="VariableExtender Modules", 
                  command=self.open_variable_extender).grid(row=2, column=1, padx=5, pady=10, sticky="ew")
        
        ttk.Button(main_frame, text="Exit", 
                  command=self.root.quit).grid(row=3, column=0, columnspan=2, pady=10, sticky="ew")
        
        # Info
        info = ttk.Label(main_frame, text="Version 1.0.0 | Made with AI",
                        font=("Arial", 8), foreground="gray")
        info.grid(row=4, column=0, columnspan=2, pady=20)
    
    def center_window(self):
        """Center window on screen."""
        self.root.update_idletasks()
        width = self.root.winfo_width()
        height = self.root.winfo_height()
        x = (self.root.winfo_screenwidth() // 2) - (width // 2)
        y = (self.root.winfo_screenheight() // 2) - (height // 2)
        self.root.geometry(f"{width}x{height}+{x}+{y}")
    
    def open_utilities(self):
        """Open utilities submenu."""
        self.root.destroy()
        root = tk.Tk()
        UtilitiesGUIMenu(root)
        root.mainloop()
    
    def open_variable_extender(self):
        """Open variable extender submenu."""
        self.root.destroy()
        root = tk.Tk()
        VariableExtenderGUIMenu(root)
        root.mainloop()


class UtilitiesGUIMenu:
    """Utilities modules GUI menu."""
    
    def __init__(self, root):
        """Initialize utilities GUI menu."""
        self.root = root
        self.root.title("Utilities - M13 Python Modules")
        self.root.geometry("600x300")
        self.root.resizable(False, False)
        
        main_frame = ttk.Frame(root, padding="20")
        main_frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        
        title = ttk.Label(main_frame, text="Utilities Modules", 
                         font=("Arial", 14, "bold"))
        title.grid(row=0, column=0, columnspan=2, pady=10)
        
        ttk.Button(main_frame, text="PydocsExport", 
                  command=self.open_pydocs).grid(row=1, column=0, padx=5, pady=10, sticky="ew")
        ttk.Button(main_frame, text="Back", 
                  command=self.go_back).grid(row=2, column=0, padx=5, pady=10, sticky="ew")
        ttk.Button(main_frame, text="Exit", 
                  command=self.root.quit).grid(row=2, column=1, padx=5, pady=10, sticky="ew")
    
    def open_pydocs(self):
        """Open PydocsExport GUI."""
        messagebox.showinfo("PydocsExport", "PydocsExport Module - Python Documentation Exporter\\n\\nExport module documentation to various formats.")
    
    def go_back(self):
        """Go back to main menu."""
        self.root.destroy()
        root = tk.Tk()
        MainGUIMenu(root)
        root.mainloop()


class VariableExtenderGUIMenu:
    """VariableExtender modules GUI menu."""
    
    def __init__(self, root):
        """Initialize VariableExtender GUI menu."""
        self.root = root
        self.root.title("VariableExtender - M13 Python Modules")
        self.root.geometry("600x400")
        self.root.resizable(False, False)
        
        main_frame = ttk.Frame(root, padding="20")
        main_frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        
        title = ttk.Label(main_frame, text="VariableExtender Modules",
                         font=("Arial", 14, "bold"))
        title.grid(row=0, column=0, columnspan=2, pady=10)
        
        ttk.Button(main_frame, text="Generic Tree",
                  command=self.open_generic_tree).grid(row=1, column=0, padx=5, pady=10, sticky="ew")
        ttk.Button(main_frame, text="MenuMaker",
                  command=self.open_menumaker).grid(row=1, column=1, padx=5, pady=10, sticky="ew")
        ttk.Button(main_frame, text="Multidimention Table",
                  command=self.open_multitable).grid(row=2, column=0, padx=5, pady=10, sticky="ew")
        ttk.Button(main_frame, text="Multidimention Paint",
                  command=self.open_paint).grid(row=2, column=1, padx=5, pady=10, sticky="ew")
        
        ttk.Button(main_frame, text="Back",
                  command=self.go_back).grid(row=3, column=0, padx=5, pady=10, sticky="ew")
        ttk.Button(main_frame, text="Exit",
                  command=self.root.quit).grid(row=3, column=1, padx=5, pady=10, sticky="ew")
    
    def open_generic_tree(self):
        """Open Generic Tree info."""
        messagebox.showinfo("Generic Tree", "Generic Tree - N-ary Tree Data Structure\\n\\nFlexible tree structure supporting any Python value types.")
    
    def open_menumaker(self):
        """Open MenuMaker info."""
        messagebox.showinfo("MenuMaker", "MenuMaker - Dynamic Menu Management\\n\\nCreate interactive menus with various item types.")
    
    def open_multitable(self):
        """Open Multitable info."""
        messagebox.showinfo("Multitable", "Multidimention Table - Multi-dimensional Arrays\\n\\nEfficient operations on multi-dimensional arrays.")
    
    def open_paint(self):
        """Open Paint info."""
        messagebox.showinfo("Paint", "Multidimention Paint - Geometric Shapes\\n\\nGeometric shapes and selection in N-dimensional space.")
    
    def go_back(self):
        """Go back to main menu."""
        self.root.destroy()
        root = tk.Tk()
        MainGUIMenu(root)
        root.mainloop()


if __name__ == "__main__":
    root = tk.Tk()
    app = MainGUIMenu(root)
    root.mainloop()
'''

# Utilities GUI
utilities_gui = '''# Generated by AI - Utilities GUI Menu
"""Utilities modules GUI menu."""

import tkinter as tk
from tkinter import ttk, messagebox


class UtilitiesGUI:
    """Utilities modules GUI."""
    
    def __init__(self, root):
        """Initialize utilities GUI."""
        self.root = root
        self.root.title("Utilities - GUI Menu")
        self.root.geometry("500x300")
        
        frame = ttk.Frame(root, padding="20")
        frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        
        ttk.Label(frame, text="Utilities Modules", 
                 font=("Arial", 14, "bold")).grid(row=0, column=0, pady=10)
        
        ttk.Button(frame, text="PydocsExport - Documentation Exporter",
                  command=self.show_pydocs).grid(row=1, column=0, pady=10, sticky="ew")
        ttk.Button(frame, text="Exit",
                  command=root.quit).grid(row=2, column=0, pady=10, sticky="ew")
    
    def show_pydocs(self):
        """Show PydocsExport info."""
        messagebox.showinfo("PydocsExport", 
            "PydocsExport Module\\n\\n"
            "Export Python module documentation to various formats.\\n"
            "Formats: HTML, PDF, Markdown, and more.")


if __name__ == "__main__":
    root = tk.Tk()
    gui = UtilitiesGUI(root)
    root.mainloop()
'''

# VariableExtender GUI
variable_extender_gui = '''# Generated by AI - VariableExtender GUI Menu
"""VariableExtender modules GUI menu."""

import tkinter as tk
from tkinter import ttk, messagebox


class VariableExtenderGUI:
    """VariableExtender modules GUI."""
    
    def __init__(self, root):
        """Initialize VariableExtender GUI."""
        self.root = root
        self.root.title("VariableExtender - GUI Menu")
        self.root.geometry("500x400")
        
        frame = ttk.Frame(root, padding="20")
        frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        
        ttk.Label(frame, text="VariableExtender Modules",
                 font=("Arial", 14, "bold")).grid(row=0, column=0, columnspan=2, pady=10)
        
        ttk.Button(frame, text="Generic Tree",
                  command=self.show_generic_tree).grid(row=1, column=0, padx=5, pady=10, sticky="ew")
        ttk.Button(frame, text="MenuMaker",
                  command=self.show_menumaker).grid(row=1, column=1, padx=5, pady=10, sticky="ew")
        ttk.Button(frame, text="Multidimention Table",
                  command=self.show_multitable).grid(row=2, column=0, padx=5, pady=10, sticky="ew")
        ttk.Button(frame, text="Multidimention Paint",
                  command=self.show_paint).grid(row=2, column=1, padx=5, pady=10, sticky="ew")
        
        ttk.Button(frame, text="Exit",
                  command=root.quit).grid(row=3, column=0, columnspan=2, pady=10, sticky="ew")
    
    def show_generic_tree(self):
        """Show Generic Tree info."""
        messagebox.showinfo("Generic Tree",
            "Generic Tree - N-ary Tree Data Structure\\n\\n"
            "Flexible tree structure supporting any Python value types with metadata support.")
    
    def show_menumaker(self):
        """Show MenuMaker info."""
        messagebox.showinfo("MenuMaker",
            "MenuMaker - Dynamic Menu Management\\n\\n"
            "Create interactive menus with text input, numeric input, checkboxes, and more.")
    
    def show_multitable(self):
        """Show Multitable info."""
        messagebox.showinfo("Multidimention Table",
            "Multidimention Table - Multi-dimensional Arrays\\n\\n"
            "Efficient operations on 1D to ND arrays with transpose, reshape, and statistical operations.")
    
    def show_paint(self):
        """Show Paint info."""
        messagebox.showinfo("Multidimention Paint",
            "Multidimention Paint - Geometric Shapes\\n\\n"
            "Geometric shapes and selection methods in N-dimensional space.")


if __name__ == "__main__":
    root = tk.Tk()
    gui = VariableExtenderGUI(root)
    root.mainloop()
'''

# Module-specific GUIs
module_gui_template = '''# Generated by AI - {module_name} GUI Module Demo
"""
{module_name} - GUI Module Demo

Interactive demonstration using tkinter.
"""

import tkinter as tk
from tkinter import ttk, messagebox


class {class_name}GUI:
    """GUI for {module_name}."""
    
    def __init__(self, root):
        """Initialize {module_name} GUI."""
        self.root = root
        self.root.title("{module_name} - GUI Demo")
        self.root.geometry("600x400")
        self.root.resizable(True, True)
        
        # Create notebook for tabs
        notebook = ttk.Notebook(root)
        notebook.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)
        
        # Info tab
        info_frame = ttk.Frame(notebook)
        notebook.add(info_frame, text="Information")
        self.setup_info_tab(info_frame)
        
        # Demo tab
        demo_frame = ttk.Frame(notebook)
        notebook.add(demo_frame, text="Demo")
        self.setup_demo_tab(demo_frame)
        
        # Help tab
        help_frame = ttk.Frame(notebook)
        notebook.add(help_frame, text="Help")
        self.setup_help_tab(help_frame)
        
        # Bottom buttons
        button_frame = ttk.Frame(root)
        button_frame.pack(side=tk.BOTTOM, fill=tk.X, padx=10, pady=10)
        
        ttk.Button(button_frame, text="Exit", command=root.quit).pack(side=tk.RIGHT)
    
    def setup_info_tab(self, frame):
        """Setup information tab."""
        info_text = ttk.Label(frame, text="{description}",
                             font=("Arial", 10), wraplength=500, justify=tk.LEFT)
        info_text.pack(padx=20, pady=20)
    
    def setup_demo_tab(self, frame):
        """Setup demo tab."""
        demo_label = ttk.Label(frame, text="Module Demo Features",
                              font=("Arial", 12, "bold"))
        demo_label.pack(pady=10)
        
        ttk.Button(frame, text="Run Example",
                  command=self.run_example).pack(pady=5)
    
    def setup_help_tab(self, frame):
        """Setup help tab."""
        help_label = ttk.Label(frame, text="Help and Documentation",
                              font=("Arial", 12, "bold"))
        help_label.pack(pady=10)
        
        help_text = tk.Text(frame, height=15, width=60, wrap=tk.WORD)
        help_text.pack(padx=10, pady=10, fill=tk.BOTH, expand=True)
        
        help_content = """
{module_name} Module Help

Features:
{features}

Usage:
See the documentation files for detailed usage instructions.

Examples:
Check the example.py files in the module directory.

Testing:
Run pytest to execute the comprehensive test suite.
        """
        help_text.insert(tk.END, help_content)
        help_text.config(state=tk.DISABLED)
    
    def run_example(self):
        """Run example."""
        messagebox.showinfo("{module_name} Example",
            "Example functionality for {module_name} would run here.")


if __name__ == "__main__":
    root = tk.Tk()
    gui = {class_name}GUI(root)
    root.mainloop()
'''

# Module definitions
modules = {
    "generic_tree": {
        "class_name": "GenericTreeGUI",
        "description": "Generic Tree - N-ary Tree Data Structure\\n\\nFlexible tree structure supporting any Python value types with metadata support, traversal, and search capabilities.",
        "features": "- N-ary tree structure\\n- Metadata support\\n- Tree traversal\\n- Node search and filtering\\n- Deep copy operations"
    },
    "MenuMaker": {
        "class_name": "MenuMakerGUI",
        "description": "MenuMaker - Dynamic Menu Management\\n\\nCreate interactive menus with text input, numeric input, checkboxes, radio buttons, and submenus.",
        "features": "- Text input items\\n- Numeric input items\\n- Checkboxes\\n- Radio buttons\\n- Submenus\\n- Internationalization"
    },
    "Multidimention_table": {
        "class_name": "MultiTableGUI",
        "description": "Multidimention Table - Multi-dimensional Arrays\\n\\nEfficient operations on 1D to ND arrays with transpose, reshape, flatten, and statistical operations.",
        "features": "- 1D to ND support\\n- Transpose operations\\n- Reshape and flatten\\n- Statistical analysis\\n- Merge and combine\\n- Slice operations"
    }
}

# Create files
files_to_create = {
    r"c:\Users\Musclor13\Documents\GitHub\M13-Python3-Modules-Collection-made-in-AI\run_gui.py": main_gui,
    r"c:\Users\Musclor13\Documents\GitHub\M13-Python3-Modules-Collection-made-in-AI\Utilities\run_gui.py": utilities_gui,
    r"c:\Users\Musclor13\Documents\GitHub\M13-Python3-Modules-Collection-made-in-AI\VariableExtender\run_gui.py": variable_extender_gui,
}

print("Generating GUI menu files (run_gui.py)...\n")

for path, content in files_to_create.items():
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"✓ Created: {os.path.basename(path)}")
    except Exception as e:
        print(f"✗ Error creating {path}: {e}")

# Create module-specific GUIs
print("\nGenerating module GUI files...\n")

module_paths = {
    "generic_tree": r"c:\Users\Musclor13\Documents\GitHub\M13-Python3-Modules-Collection-made-in-AI\VariableExtender\generic_tree\run_gui.py",
    "MenuMaker": r"c:\Users\Musclor13\Documents\GitHub\M13-Python3-Modules-Collection-made-in-AI\VariableExtender\MenuMaker\run_gui.py",
    "Multidimention_table": r"c:\Users\Musclor13\Documents\GitHub\M13-Python3-Modules-Collection-made-in-AI\VariableExtender\Multidimention_table\run_gui.py",
}

for module, path in module_paths.items():
    try:
        info = modules[module]
        content = module_gui_template.format(
            module_name=module,
            class_name=info["class_name"],
            description=info["description"],
            features=info["features"]
        )
        
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"✓ Created: {module}/run_gui.py")
    except Exception as e:
        print(f"✗ Error creating {module} GUI: {e}")

print("\nGUI menu files generated successfully!")
