# Generated by AI - Main Module Runner
"""
M13 Python Modules Collection - Main Runner

Interactive menu to select and run modules.
"""

import os
import sys
import subprocess

def show_menu():
    print("\n" + "=" * 60)
    print("  M13 Python Modules Collection - Main Menu")
    print("=" * 60)
    print("  1. Utilities Modules")
    print("  2. VariableExtender Modules")
    print("  3. Exit")
    print("=" * 60)

def main():
    while True:
        show_menu()
        choice = input("\n  Select category (1-3): ").strip()
        
        if choice == "1":
            subprocess.run([sys.executable, "Utilities/run.py"])
        elif choice == "2":
            subprocess.run([sys.executable, "VariableExtender/run.py"])
        elif choice == "3":
            print("\n  Goodbye!")
            break
        else:
            print("  Invalid choice.")

if __name__ == "__main__":
    main()
