# Generated by AI - Main GUI Menu
"""
M13 Python Modules Collection - GUI Menu

Interactive graphical menu using tkinter to select and run modules.
"""

import tkinter as tk
from tkinter import ttk, messagebox
import subprocess
import sys
from pathlib import Path


class MainGUIMenu:
    """Main menu GUI using tkinter."""
    
    def __init__(self, root):
        """Initialize main GUI menu."""
        self.root = root
        self.root.title("M13 Python Modules Collection")
        self.root.geometry("600x400")
        self.root.resizable(False, False)
        
        # Center window
        self.center_window()
        
        # Create main frame
        main_frame = ttk.Frame(root, padding="20")
        main_frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        
        # Title
        title = ttk.Label(main_frame, text="M13 Python Modules Collection", 
                         font=("Arial", 16, "bold"))
        title.grid(row=0, column=0, columnspan=2, pady=10)
        
        # Subtitle
        subtitle = ttk.Label(main_frame, text="Select a module category",
                            font=("Arial", 10))
        subtitle.grid(row=1, column=0, columnspan=2, pady=5)
        
        # Buttons
        ttk.Button(main_frame, text="Utilities Modules", 
                  command=self.open_utilities).grid(row=2, column=0, padx=5, pady=10, sticky="ew")
        ttk.Button(main_frame, text="VariableExtender Modules", 
                  command=self.open_variable_extender).grid(row=2, column=1, padx=5, pady=10, sticky="ew")
        
        ttk.Button(main_frame, text="Exit", 
                  command=self.root.quit).grid(row=3, column=0, columnspan=2, pady=10, sticky="ew")
        
        # Info
        info = ttk.Label(main_frame, text="Version 1.0.0 | Made with AI",
                        font=("Arial", 8), foreground="gray")
        info.grid(row=4, column=0, columnspan=2, pady=20)
    
    def center_window(self):
        """Center window on screen."""
        self.root.update_idletasks()
        width = self.root.winfo_width()
        height = self.root.winfo_height()
        x = (self.root.winfo_screenwidth() // 2) - (width // 2)
        y = (self.root.winfo_screenheight() // 2) - (height // 2)
        self.root.geometry(f"{width}x{height}+{x}+{y}")
    
    def open_utilities(self):
        """Open utilities submenu."""
        self.root.destroy()
        root = tk.Tk()
        UtilitiesGUIMenu(root)
        root.mainloop()
    
    def open_variable_extender(self):
        """Open variable extender submenu."""
        self.root.destroy()
        root = tk.Tk()
        VariableExtenderGUIMenu(root)
        root.mainloop()


class UtilitiesGUIMenu:
    """Utilities modules GUI menu."""
    
    def __init__(self, root):
        """Initialize utilities GUI menu."""
        self.root = root
        self.root.title("Utilities - M13 Python Modules")
        self.root.geometry("600x300")
        self.root.resizable(False, False)
        
        main_frame = ttk.Frame(root, padding="20")
        main_frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        
        title = ttk.Label(main_frame, text="Utilities Modules", 
                         font=("Arial", 14, "bold"))
        title.grid(row=0, column=0, columnspan=2, pady=10)
        
        ttk.Button(main_frame, text="PydocsExport", 
                  command=self.open_pydocs).grid(row=1, column=0, padx=5, pady=10, sticky="ew")
        ttk.Button(main_frame, text="Back", 
                  command=self.go_back).grid(row=2, column=0, padx=5, pady=10, sticky="ew")
        ttk.Button(main_frame, text="Exit", 
                  command=self.root.quit).grid(row=2, column=1, padx=5, pady=10, sticky="ew")
    
    def open_pydocs(self):
        """Open PydocsExport GUI."""
        messagebox.showinfo("PydocsExport", "PydocsExport Module - Python Documentation Exporter\n\nExport module documentation to various formats.")
    
    def go_back(self):
        """Go back to main menu."""
        self.root.destroy()
        root = tk.Tk()
        MainGUIMenu(root)
        root.mainloop()


class VariableExtenderGUIMenu:
    """VariableExtender modules GUI menu."""
    
    def __init__(self, root):
        """Initialize VariableExtender GUI menu."""
        self.root = root
        self.root.title("VariableExtender - M13 Python Modules")
        self.root.geometry("600x400")
        self.root.resizable(False, False)
        
        main_frame = ttk.Frame(root, padding="20")
        main_frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        
        title = ttk.Label(main_frame, text="VariableExtender Modules",
                         font=("Arial", 14, "bold"))
        title.grid(row=0, column=0, columnspan=2, pady=10)
        
        ttk.Button(main_frame, text="Generic Tree",
                  command=self.open_generic_tree).grid(row=1, column=0, padx=5, pady=10, sticky="ew")
        ttk.Button(main_frame, text="MenuMaker",
                  command=self.open_menumaker).grid(row=1, column=1, padx=5, pady=10, sticky="ew")
        ttk.Button(main_frame, text="Multidimention Table",
                  command=self.open_multitable).grid(row=2, column=0, padx=5, pady=10, sticky="ew")
        ttk.Button(main_frame, text="Multidimention Paint",
                  command=self.open_paint).grid(row=2, column=1, padx=5, pady=10, sticky="ew")
        
        ttk.Button(main_frame, text="Back",
                  command=self.go_back).grid(row=3, column=0, padx=5, pady=10, sticky="ew")
        ttk.Button(main_frame, text="Exit",
                  command=self.root.quit).grid(row=3, column=1, padx=5, pady=10, sticky="ew")
    
    def open_generic_tree(self):
        """Open Generic Tree info."""
        messagebox.showinfo("Generic Tree", "Generic Tree - N-ary Tree Data Structure\n\nFlexible tree structure supporting any Python value types.")
    
    def open_menumaker(self):
        """Open MenuMaker info."""
        messagebox.showinfo("MenuMaker", "MenuMaker - Dynamic Menu Management\n\nCreate interactive menus with various item types.")
    
    def open_multitable(self):
        """Open Multitable info."""
        messagebox.showinfo("Multitable", "Multidimention Table - Multi-dimensional Arrays\n\nEfficient operations on multi-dimensional arrays.")
    
    def open_paint(self):
        """Open Paint info."""
        messagebox.showinfo("Paint", "Multidimention Paint - Geometric Shapes\n\nGeometric shapes and selection in N-dimensional space.")
    
    def go_back(self):
        """Go back to main menu."""
        self.root.destroy()
        root = tk.Tk()
        MainGUIMenu(root)
        root.mainloop()


if __name__ == "__main__":
    root = tk.Tk()
    app = MainGUIMenu(root)
    root.mainloop()
