# Generated by AI - Update pyproject.toml for comprehensive testing

"""Update pyproject.toml to reflect new test infrastructure and GUI support."""

import os
import sys

# Read current pyproject.toml
pyproject_path = r"c:\Users\Musclor13\Documents\GitHub\M13-Python3-Modules-Collection-made-in-AI\pyproject.toml"

with open(pyproject_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Update pyproject.toml with test and GUI information
new_pyproject = '''[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "M13aiCollection"
version = "1.0.0"
description = "Comprehensive Python modules collection: GenericTree, MenuMaker, MultiTable, PydocsExport, and utilities. Features console (run.py) and GUI (run_gui.py with tkinter) interfaces for all modules. Includes extensive test coverage."
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
    {name = "Generated by AI", email = "ai@generation.com"}
]
keywords = [
    "tree",
    "menu",
    "table",
    "multidimensional",
    "utilities",
    "documentation",
    "gui",
    "tkinter"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Environment :: X11 Applications :: Tk",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Natural Language :: French",
    "Natural Language :: Spanish",
    "Natural Language :: German",
    "Natural Language :: Italian",
    "Natural Language :: Portuguese",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
    "black>=23.0",
    "flake8>=6.0",
    "mypy>=1.0",
    "sphinx>=5.0",
]
test = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
    "pytest-mock>=3.10",
]
gui = []  # tkinter is included in Python standard library

[project.urls]
Homepage = "https://github.com/Musclor13/M13-Python3-Modules-Collection-made-in-AI"
Documentation = "https://github.com/Musclor13/M13-Python3-Modules-Collection-made-in-AI#readme"
Repository = "https://github.com/Musclor13/M13-Python3-Modules-Collection-made-in-AI.git"
Issues = "https://github.com/Musclor13/M13-Python3-Modules-Collection-made-in-AI/issues"

[tool.setuptools]
packages = ["Utilities", "VariableExtender"]

[tool.setuptools.package-dir]
"" = "."

[tool.setuptools.package-data]
Utilities = ["**/*.py", "**/*.md", "**/*.txt"]
VariableExtender = ["**/*.py", "**/*.md", "**/*.txt"]

[tool.pytest.ini_options]
testpaths = [
    "Utilities/PydocsExport",
    "VariableExtender/generic_tree",
    "VariableExtender/MenuMaker",
    "VariableExtender/Multidimention_table",
]
addopts = "-v --tb=short --strict-markers"
markers = [
    "unit: unit tests",
    "integration: integration tests",
    "slow: slow running tests",
    "gui: GUI-related tests",
]

[tool.coverage.run]
source = [
    "Utilities",
    "VariableExtender",
]
omit = [
    "*/tests/*",
    "*/test_*.py",
    "*/__pycache__/*",
    "*/venv/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "class .*\\\\(Protocol\\\\):",
    "@(abc\\\\.)?abstractmethod",
]

[tool.black]
line-length = 100
target-version = ["py37", "py38", "py39", "py310", "py311", "py312", "py313"]
include = "\\\\.pyi?$"
extend-exclude = """
/(
  # directories
  \\\\.eggs
  | \\\\.git
  | \\\\.hg
  | \\\\.mypy_cache
  | \\\\.tox
  | \\\\.venv
  | build
  | dist
)/
"""

[tool.isort]
profile = "black"
line_length = 100
multi_line_mode = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
python_version = "3.7"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true

[tool.pylint.messages_control]
disable = [
    "C0330", "C0326",  # Bad whitespace
    "R0913",  # Too many arguments
    "R0914",  # Too many local variables
]
'''

with open(pyproject_path, 'w', encoding='utf-8') as f:
    f.write(new_pyproject)

print("✓ Updated pyproject.toml with test and GUI configuration")
