# Generated by AI - VariableExtender Module Runner
"""
VariableExtender Modules Runner

Interactive menu for variable extender modules.
"""

import os
import sys
import subprocess

def show_menu():
    print("\n" + "=" * 60)
    print("  VariableExtender - Module Selector")
    print("=" * 60)
    print("  1. generic_tree - N-ary tree structure")
    print("  2. MenuMaker - Dynamic menu management")
    print("  3. Multidimention_table - Multi-dimensional arrays")
    print("  4. Back to Main Menu")
    print("  5. Exit")
    print("=" * 60)

def main():
    while True:
        show_menu()
        choice = input("\n  Select (1-5): ").strip()
        
        if choice == "1":
            subprocess.run([sys.executable, "generic_tree/run.py"])
        elif choice == "2":
            subprocess.run([sys.executable, "MenuMaker/run.py"])
        elif choice == "3":
            subprocess.run([sys.executable, "Multidimention_table/run.py"])
        elif choice == "4":
            break
        elif choice == "5":
            sys.exit(0)
        else:
            print("  Invalid choice.")

if __name__ == "__main__":
    main()
