# Generated by AI - VariableExtender GUI Menu
"""VariableExtender modules GUI menu."""

import tkinter as tk
from tkinter import ttk, messagebox


class VariableExtenderGUI:
    """VariableExtender modules GUI."""
    
    def __init__(self, root):
        """Initialize VariableExtender GUI."""
        self.root = root
        self.root.title("VariableExtender - GUI Menu")
        self.root.geometry("500x400")
        
        frame = ttk.Frame(root, padding="20")
        frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        
        ttk.Label(frame, text="VariableExtender Modules",
                 font=("Arial", 14, "bold")).grid(row=0, column=0, columnspan=2, pady=10)
        
        ttk.Button(frame, text="Generic Tree",
                  command=self.show_generic_tree).grid(row=1, column=0, padx=5, pady=10, sticky="ew")
        ttk.Button(frame, text="MenuMaker",
                  command=self.show_menumaker).grid(row=1, column=1, padx=5, pady=10, sticky="ew")
        ttk.Button(frame, text="Multidimention Table",
                  command=self.show_multitable).grid(row=2, column=0, padx=5, pady=10, sticky="ew")
        ttk.Button(frame, text="Multidimention Paint",
                  command=self.show_paint).grid(row=2, column=1, padx=5, pady=10, sticky="ew")
        
        ttk.Button(frame, text="Exit",
                  command=root.quit).grid(row=3, column=0, columnspan=2, pady=10, sticky="ew")
    
    def show_generic_tree(self):
        """Show Generic Tree info."""
        messagebox.showinfo("Generic Tree",
            "Generic Tree - N-ary Tree Data Structure\n\n"
            "Flexible tree structure supporting any Python value types with metadata support.")
    
    def show_menumaker(self):
        """Show MenuMaker info."""
        messagebox.showinfo("MenuMaker",
            "MenuMaker - Dynamic Menu Management\n\n"
            "Create interactive menus with text input, numeric input, checkboxes, and more.")
    
    def show_multitable(self):
        """Show Multitable info."""
        messagebox.showinfo("Multidimention Table",
            "Multidimention Table - Multi-dimensional Arrays\n\n"
            "Efficient operations on 1D to ND arrays with transpose, reshape, and statistical operations.")
    
    def show_paint(self):
        """Show Paint info."""
        messagebox.showinfo("Multidimention Paint",
            "Multidimention Paint - Geometric Shapes\n\n"
            "Geometric shapes and selection methods in N-dimensional space.")


if __name__ == "__main__":
    root = tk.Tk()
    gui = VariableExtenderGUI(root)
    root.mainloop()
