# Generated by AI - Utilities Module Runner
"""
Utilities Modules Runner

Interactive menu for utilities.
"""

import os
import sys
import subprocess

def show_menu():
    print("\n" + "=" * 60)
    print("  Utilities - Module Selector")
    print("=" * 60)
    print("  1. PydocsExport - Export Python documentation")
    print("  2. Back to Main Menu")
    print("  3. Exit")
    print("=" * 60)

def main():
    while True:
        show_menu()
        choice = input("\n  Select (1-3): ").strip()
        
        if choice == "1":
            subprocess.run([sys.executable, "PydocsExport/run.py"])
        elif choice == "2":
            break
        elif choice == "3":
            sys.exit(0)
        else:
            print("  Invalid choice.")

if __name__ == "__main__":
    main()
