# Generated by AI - Python Module

"""
This module was generated/enhanced by AI Assistant.
Provides professional-grade functionality with Python.
"""

# -*- coding: utf-8 -*-
"""
MenuMaker Example - Demonstrating key features and usage patterns.

This example shows how to create and manage menus with MenuMaker.
"""

from MenuMaker import Menu, MenuSystem, ItemType


def example_1_simple_menu():
    """Example 1: Create a simple menu."""
    print("\n" + "="*60)
    print("EXAMPLE 1: Simple Menu")
    print("="*60)
    
    menu = Menu("main", label="Main Menu")
    menu.add_action("start", "Start Game")
    menu.add_action("settings", "Settings")
    menu.add_action("quit", "Quit")
    
    print("\nMenu items:")
    for item in menu.get_visible_items():
        print(f"  - {item.label}")


def example_2_form_with_validation():
    """Example 2: Create a form with validation."""
    print("\n" + "="*60)
    print("EXAMPLE 2: Form with Validation")
    print("="*60)
    
    form = Menu("registration", label="Registration Form")
    form.add_text_input("username", "Username", default="")
    form.add_text_input("email", "Email", default="")
    form.add_numeric_input("age", "Age", default=18, min_val=13, max_val=120)
    form.add_checkbox("terms", "I agree to terms", default=False)
    
    # Fill the form
    form.set_all_values({
        "username": "john_doe",
        "email": "john@example.com",
        "age": 25,
        "terms": True
    })
    
    print("\nForm values:")
    for key, value in form.get_all_values().items():
        print(f"  {key}: {value}")


def example_3_configuration_menu():
    """Example 3: Create a configuration menu."""
    print("\n" + "="*60)
    print("EXAMPLE 3: Game Configuration Menu")
    print("="*60)
    
    config = Menu("game_config", label="Game Configuration")
    
    # Graphics settings
    config.add_numeric_input("width", "Screen Width", 
                            default=1920, min_val=800, max_val=3840)
    config.add_numeric_input("height", "Screen Height", 
                            default=1080, min_val=600, max_val=2160)
    config.add_radio("quality", "Graphics Quality",
                    options=["Low", "Medium", "High", "Ultra"],
                    default="High")
    config.add_checkbox("fullscreen", "Fullscreen Mode", default=False)
    
    config.add_separator()
    
    # Audio settings
    config.add_numeric_input("volume", "Master Volume", 
                            default=80, min_val=0, max_val=100)
    config.add_checkbox("effects", "Sound Effects", default=True)
    
    print("\nConfiguration items:")
    for item in config.get_visible_items():
        if item.item_type != ItemType.SEPARATOR:
            value = config.get_value(item.identifier)
            print(f"  {item.label}: {value}")


def example_4_hierarchical_menu():
    """Example 4: Create hierarchical menus with submenus."""
    print("\n" + "="*60)
    print("EXAMPLE 4: Hierarchical Menu with Submenus")
    print("="*60)
    
    main = Menu("main", label="Main Menu")
    
    # Game submenu
    game = Menu("game", label="Game")
    game.add_action("new_game", "New Game")
    game.add_action("load_game", "Load Game")
    game.add_action("save_game", "Save Game")
    main.add_submenu("game_id", "Game", game)
    
    # Settings submenu
    settings = Menu("settings", label="Settings")
    settings.add_numeric_input("difficulty", "Difficulty", 
                              default=1, min_val=1, max_val=5)
    settings.add_radio("language", "Language",
                      options=["English", "Français", "Español"],
                      default="English")
    main.add_submenu("settings_id", "Settings", settings)
    
    # Help submenu
    help_menu = Menu("help", label="Help")
    help_menu.add_action("about", "About")
    help_menu.add_action("controls", "Controls")
    main.add_submenu("help_id", "Help", help_menu)
    
    print("\nMain menu structure:")
    for item in main.get_visible_items():
        print(f"  - {item.label}")
        if item.item_type == ItemType.SUBMENU:
            submenu = item.submenu
            print(f"    Submenu items: {len(submenu.items)}")
            for sub_item in submenu.get_visible_items():
                print(f"      * {sub_item.label}")


def example_5_callbacks():
    """Example 5: Use callbacks for actions."""
    print("\n" + "="*60)
    print("EXAMPLE 5: Callbacks and Actions")
    print("="*60)
    
    def on_start(item):
        return "Game started successfully!"
    
    def on_settings(item):
        return "Settings opened."
    
    menu = Menu("game", label="Game Menu")
    menu.add_action("start", "Start Game", callback=on_start)
    menu.add_action("settings", "Settings", callback=on_settings)
    menu.add_action("quit", "Quit")
    
    print("\nExecuting callbacks:")
    for item_id in ["start", "settings", "quit"]:
        item = menu.get_item(item_id)
        result = item.execute()
        print(f"  {item.label}: {result if result else '(no callback)'}")


def example_6_item_control():
    """Example 6: Control item visibility and state."""
    print("\n" + "="*60)
    print("EXAMPLE 6: Item Control (Enable/Disable/Show/Hide)")
    print("="*60)
    
    menu = Menu("test", label="Test Menu")
    menu.add_action("always_visible", "Always Visible")
    menu.add_action("sometimes_hidden", "Sometimes Hidden")
    menu.add_action("admin_only", "Admin Only (disabled)")
    
    # Hide one item
    menu.hide_item("sometimes_hidden")
    
    # Disable admin item
    menu.disable_item("admin_only")
    
    print("\nAll items:")
    for item in menu.items.values():
        status = []
        if not item.visible:
            status.append("HIDDEN")
        if not item.enabled:
            status.append("DISABLED")
        status_str = f" [{', '.join(status)}]" if status else ""
        print(f"  - {item.label}{status_str}")
    
    print("\nVisible items only:")
    for item in menu.get_visible_items():
        print(f"  - {item.label}")
    
    print("\nEnabled items only:")
    for item in menu.get_enabled_items():
        print(f"  - {item.label}")


def example_7_menu_system_i18n():
    """Example 7: Using MenuSystem with internationalization."""
    print("\n" + "="*60)
    print("EXAMPLE 7: MenuSystem with i18n Support")
    print("="*60)
    
    # Create a menu system
    system = MenuSystem(default_language="en")
    
    # Create menus
    main = system.create_menu("main", label="Main Menu")
    main.add_action("play", "Play Game")
    main.add_action("options", "Options")
    main.add_action("exit", "Exit")
    
    settings = system.create_menu("settings", label="Settings")
    settings.add_radio("lang", "Language",
                      options=["English", "Français"],
                      default="English")
    
    print(f"\nMenuSystem created with {len(system.menus)} menu(s)")
    print(f"Current language: {system.current_language}")
    
    print("\nMainMenu items:")
    for item in main.get_visible_items():
        print(f"  - {item.label}")
    
    # Change language
    print(f"\nChanging language to: fr")
    system.set_language("fr")
    print(f"Current language: {system.current_language}")


def example_8_complex_form():
    """Example 8: Complex multi-section form."""
    print("\n" + "="*60)
    print("EXAMPLE 8: Complex Multi-Section Form")
    print("="*60)
    
    form = Menu("account", label="Account Setup")
    
    # Personal information
    form.add_text_input("first_name", "First Name")
    form.add_text_input("last_name", "Last Name")
    form.add_text_input("email", "Email Address")
    form.add_separator()
    
    # Account details
    form.add_text_input("username", "Username")
    form.add_text_input("password", "Password")
    form.add_checkbox("newsletter", "Subscribe to newsletter", default=True)
    form.add_separator()
    
    # Preferences
    form.add_radio("theme", "Color Theme",
                  options=["Light", "Dark", "Auto"],
                  default="Auto")
    form.add_numeric_input("font_size", "Font Size", 
                          default=12, min_val=10, max_val=24)
    form.add_checkbox("notifications", "Enable notifications", default=True)
    
    # Fill the form
    form.set_all_values({
        "first_name": "Alice",
        "last_name": "Smith",
        "email": "alice@example.com",
        "username": "alice123",
        "password": "secure_password",
        "newsletter": True,
        "theme": "Dark",
        "font_size": 14,
        "notifications": True
    })
    
    print("\nForm sections:")
    print("  Personal Information:")
    for key in ["first_name", "last_name", "email"]:
        value = form.get_value(key)
        print(f"    {key}: {value}")
    
    print("  Account Details:")
    for key in ["username", "newsletter"]:
        value = form.get_value(key)
        print(f"    {key}: {value}")
    
    print("  Preferences:")
    for key in ["theme", "font_size", "notifications"]:
        value = form.get_value(key)
        print(f"    {key}: {value}")


def main():
    """Run all examples."""
    print("\n" + "#"*60)
    print("# MenuMaker - Feature Examples")
    print("#"*60)
    
    example_1_simple_menu()
    example_2_form_with_validation()
    example_3_configuration_menu()
    example_4_hierarchical_menu()
    example_5_callbacks()
    example_6_item_control()
    example_7_menu_system_i18n()
    example_8_complex_form()
    
    print("\n" + "#"*60)
    print("# All examples completed successfully!")
    print("#"*60 + "\n")


if __name__ == "__main__":
    main()
