# Generated by AI - MenuMaker Demo
"""MenuMaker module demonstration."""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

from menu import Menu, TextInput, NumericInput

print("\nMenuMaker - Interactive Menu Demo")
print("=" * 60)

menu = Menu("Main Menu")
menu.add_item(TextInput("name", "Your name: "))
menu.add_item(NumericInput("age", "Your age: "))

print("\nSee menu.py for full documentation")
print("Run: menu.py in this directory")
