# Generated by AI - MenuMaker GUI Module Demo
"""
MenuMaker - GUI Module Demo

Interactive demonstration using tkinter.
"""

import tkinter as tk
from tkinter import ttk, messagebox


class MenuMakerGUIGUI:
    """GUI for MenuMaker."""
    
    def __init__(self, root):
        """Initialize MenuMaker GUI."""
        self.root = root
        self.root.title("MenuMaker - GUI Demo")
        self.root.geometry("600x400")
        self.root.resizable(True, True)
        
        # Create notebook for tabs
        notebook = ttk.Notebook(root)
        notebook.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)
        
        # Info tab
        info_frame = ttk.Frame(notebook)
        notebook.add(info_frame, text="Information")
        self.setup_info_tab(info_frame)
        
        # Demo tab
        demo_frame = ttk.Frame(notebook)
        notebook.add(demo_frame, text="Demo")
        self.setup_demo_tab(demo_frame)
        
        # Help tab
        help_frame = ttk.Frame(notebook)
        notebook.add(help_frame, text="Help")
        self.setup_help_tab(help_frame)
        
        # Bottom buttons
        button_frame = ttk.Frame(root)
        button_frame.pack(side=tk.BOTTOM, fill=tk.X, padx=10, pady=10)
        
        ttk.Button(button_frame, text="Exit", command=root.quit).pack(side=tk.RIGHT)
    
    def setup_info_tab(self, frame):
        """Setup information tab."""
        info_text = ttk.Label(frame, text="MenuMaker - Dynamic Menu Management\n\nCreate interactive menus with text input, numeric input, checkboxes, radio buttons, and submenus.",
                             font=("Arial", 10), wraplength=500, justify=tk.LEFT)
        info_text.pack(padx=20, pady=20)
    
    def setup_demo_tab(self, frame):
        """Setup demo tab."""
        demo_label = ttk.Label(frame, text="Module Demo Features",
                              font=("Arial", 12, "bold"))
        demo_label.pack(pady=10)
        
        ttk.Button(frame, text="Run Example",
                  command=self.run_example).pack(pady=5)
    
    def setup_help_tab(self, frame):
        """Setup help tab."""
        help_label = ttk.Label(frame, text="Help and Documentation",
                              font=("Arial", 12, "bold"))
        help_label.pack(pady=10)
        
        help_text = tk.Text(frame, height=15, width=60, wrap=tk.WORD)
        help_text.pack(padx=10, pady=10, fill=tk.BOTH, expand=True)
        
        help_content = """
MenuMaker Module Help

Features:
- Text input items\n- Numeric input items\n- Checkboxes\n- Radio buttons\n- Submenus\n- Internationalization

Usage:
See the documentation files for detailed usage instructions.

Examples:
Check the example.py files in the module directory.

Testing:
Run pytest to execute the comprehensive test suite.
        """
        help_text.insert(tk.END, help_content)
        help_text.config(state=tk.DISABLED)
    
    def run_example(self):
        """Run example."""
        messagebox.showinfo("MenuMaker Example",
            "Example functionality for MenuMaker would run here.")


if __name__ == "__main__":
    root = tk.Tk()
    gui = MenuMakerGUIGUI(root)
    root.mainloop()
