# Generated by AI - MenuMaker Comprehensive Tests
"""
Comprehensive test suite for MenuMaker module.
"""

import pytest
from io import StringIO
import sys
from menu import Menu, TextInput, NumericInput, CheckboxItem, RadioButton


class TestMenuBasics:
    """Test basic menu operations."""
    
    def test_create_menu(self):
        """Test creating a menu."""
        menu = Menu("Test Menu")
        assert menu.title == "Test Menu"
        assert len(menu.items) == 0
    
    def test_add_text_input(self):
        """Test adding text input item."""
        menu = Menu("Test")
        item = TextInput("name", "Enter name: ")
        menu.add_item(item)
        assert len(menu.items) == 1
    
    def test_add_numeric_input(self):
        """Test adding numeric input item."""
        menu = Menu("Test")
        item = NumericInput("age", "Enter age: ")
        menu.add_item(item)
        assert len(menu.items) == 1


class TestMenuItems:
    """Test menu item types."""
    
    def test_text_input_item(self):
        """Test text input item."""
        item = TextInput("test", "Prompt: ")
        assert item.name == "test"
        assert item.prompt == "Prompt: "
    
    def test_numeric_input_item(self):
        """Test numeric input item."""
        item = NumericInput("number", "Number: ")
        assert item.name == "number"
    
    def test_checkbox_item(self):
        """Test checkbox item."""
        item = CheckboxItem("agree", "I agree")
        assert item.name == "agree"


class TestMenuValidation:
    """Test input validation."""
    
    def test_numeric_validation(self):
        """Test numeric input validation."""
        item = NumericInput("age", "Age: ")
        # Test validation logic


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
