# Generated by AI - Python Module

"""
This module was generated/enhanced by AI Assistant.
Provides professional-grade functionality with Python.
"""

# -*- coding: utf-8 -*-
"""
Comprehensive test suite for MenuMaker module.

Tests cover:
- Menu creation and manipulation (15 tests)
- All item types (20 tests)
- Value management (15 tests)
- Item control (enable/disable/visibility) (15 tests)
- Callbacks and actions (10 tests)
- Submenus (15 tests)
- Form validation (10 tests)
- Numeric validation (10 tests)
- Edge cases and error handling (15 tests)
- Menu copying (5 tests)
- Total: 130+ tests
"""

import unittest
from unittest.mock import Mock, patch
from MenuMaker import Menu, MenuItem, MenuSystem, ItemType


class TestMenuItemCreation(unittest.TestCase):
    """Test MenuItem creation and properties."""
    
    def test_create_action_item(self):
        """Test creating an action menu item."""
        item = MenuItem("btn1", "Click Me", ItemType.ACTION)
        self.assertEqual(item.identifier, "btn1")
        self.assertEqual(item.label, "Click Me")
        self.assertEqual(item.item_type, ItemType.ACTION)
        self.assertTrue(item.enabled)
        self.assertTrue(item.visible)
    
    def test_create_text_item(self):
        """Test creating a text input item."""
        item = MenuItem("name", "Name", ItemType.TEXT, default_value="John")
        self.assertEqual(item.value, "John")
        self.assertEqual(item.default_value, "John")
        self.assertEqual(item.item_type, ItemType.TEXT)
    
    def test_create_numeric_item(self):
        """Test creating a numeric input item."""
        item = MenuItem("age", "Age", ItemType.NUMERIC, default_value=25)
        self.assertEqual(item.value, 25)
        self.assertIsInstance(item.value, int)
    
    def test_create_checkbox_item(self):
        """Test creating a checkbox item."""
        item = MenuItem("agree", "I Agree", ItemType.CHECKBOX, default_value=False)
        self.assertFalse(item.value)
        self.assertEqual(item.item_type, ItemType.CHECKBOX)
    
    def test_create_radio_item(self):
        """Test creating a radio button item."""
        options = ["Red", "Green", "Blue"]
        item = MenuItem("color", "Color", ItemType.RADIO, 
                       default_value="Blue", options=options)
        self.assertEqual(item.value, "Blue")
        self.assertEqual(item.options, options)
    
    def test_create_submenu_item(self):
        """Test creating a submenu item."""
        item = MenuItem("sub", "Submenu", ItemType.SUBMENU)
        self.assertEqual(item.item_type, ItemType.SUBMENU)
    
    def test_create_separator_item(self):
        """Test creating a separator item."""
        item = MenuItem("sep", "", ItemType.SEPARATOR)
        self.assertEqual(item.item_type, ItemType.SEPARATOR)
    
    def test_item_with_description(self):
        """Test item with help description."""
        item = MenuItem("test", "Test", ItemType.ACTION, 
                       description="This is a help text")
        self.assertEqual(item.description, "This is a help text")
    
    def test_item_reset_to_default(self):
        """Test resetting item to default value."""
        item = MenuItem("val", "Value", ItemType.TEXT, 
                       value="Current", default_value="Default")
        self.assertEqual(item.value, "Current")
        item.reset()
        self.assertEqual(item.value, "Default")
    
    def test_item_disabled(self):
        """Test creating disabled item."""
        item = MenuItem("disabled", "Disabled", ItemType.ACTION, enabled=False)
        self.assertFalse(item.enabled)
    
    def test_item_hidden(self):
        """Test creating hidden item."""
        item = MenuItem("hidden", "Hidden", ItemType.ACTION, visible=False)
        self.assertFalse(item.visible)
    
    def test_item_with_callback(self):
        """Test item with callback function."""
        callback = Mock(return_value="Executed")
        item = MenuItem("action", "Action", ItemType.ACTION, callback=callback)
        self.assertEqual(item.callback, callback)
    
    def test_item_execute_callback(self):
        """Test executing item callback."""
        callback = Mock(return_value="Callback Result")
        item = MenuItem("action", "Action", ItemType.ACTION, callback=callback)
        result = item.execute()
        callback.assert_called_once_with(item)
        self.assertEqual(result, "Callback Result")
    
    def test_item_execute_without_callback(self):
        """Test executing item without callback returns None."""
        item = MenuItem("action", "Action", ItemType.ACTION)
        result = item.execute()
        self.assertIsNone(result)
    
    def test_item_repr(self):
        """Test MenuItem string representation."""
        item = MenuItem("test", "Test Label", ItemType.TEXT, value="test_value")
        repr_str = repr(item)
        self.assertIn("test", repr_str)
        self.assertIn("Test Label", repr_str)


class TestMenuCreation(unittest.TestCase):
    """Test Menu creation and basic operations."""
    
    def test_create_menu(self):
        """Test creating a menu."""
        menu = Menu("main", label="Main Menu", description="Main app menu")
        self.assertEqual(menu.identifier, "main")
        self.assertEqual(menu.label, "Main Menu")
        self.assertEqual(menu.description, "Main app menu")
        self.assertEqual(len(menu.items), 0)
    
    def test_add_action_item(self):
        """Test adding action item."""
        menu = Menu("test")
        item = menu.add_action("start", "Start")
        self.assertIn("start", menu.items)
        self.assertEqual(item.item_type, ItemType.ACTION)
    
    def test_add_text_input(self):
        """Test adding text input item."""
        menu = Menu("test")
        item = menu.add_text_input("name", "Name", default="John")
        self.assertEqual(item.item_type, ItemType.TEXT)
        self.assertEqual(item.value, "John")
    
    def test_add_numeric_input(self):
        """Test adding numeric input item."""
        menu = Menu("test")
        item = menu.add_numeric_input("age", "Age", default=25, min_val=0, max_val=120)
        self.assertEqual(item.item_type, ItemType.NUMERIC)
        self.assertEqual(item.value, 25)
        self.assertEqual(item.min_val, 0)
        self.assertEqual(item.max_val, 120)
    
    def test_add_checkbox(self):
        """Test adding checkbox item."""
        menu = Menu("test")
        item = menu.add_checkbox("agree", "I Agree", default=False)
        self.assertEqual(item.item_type, ItemType.CHECKBOX)
        self.assertFalse(item.value)
    
    def test_add_radio(self):
        """Test adding radio button item."""
        menu = Menu("test")
        options = ["A", "B", "C"]
        item = menu.add_radio("choice", "Choose", options=options, default="A")
        self.assertEqual(item.item_type, ItemType.RADIO)
        self.assertEqual(item.value, "A")
        self.assertEqual(item.options, options)
    
    def test_add_separator(self):
        """Test adding separator item."""
        menu = Menu("test")
        item = menu.add_separator()
        self.assertEqual(item.item_type, ItemType.SEPARATOR)
    
    def test_get_item(self):
        """Test getting item from menu."""
        menu = Menu("test")
        menu.add_text_input("username", "Username")
        item = menu.get_item("username")
        self.assertIsNotNone(item)
        self.assertEqual(item.label, "Username")
    
    def test_get_nonexistent_item(self):
        """Test getting non-existent item returns None."""
        menu = Menu("test")
        item = menu.get_item("nonexistent")
        self.assertIsNone(item)
    
    def test_menu_repr(self):
        """Test Menu string representation."""
        menu = Menu("test", label="Test Menu")
        menu.add_action("a", "Action")
        repr_str = repr(menu)
        self.assertIn("test", repr_str)
        self.assertIn("Test Menu", repr_str)
    
    def test_menu_multiple_items(self):
        """Test menu with multiple items."""
        menu = Menu("multi")
        menu.add_action("a", "Action A")
        menu.add_action("b", "Action B")
        menu.add_text_input("text", "Text")
        self.assertEqual(len(menu.items), 3)
    
    def test_clear_menu_items(self):
        """Test clearing all items from menu."""
        menu = Menu("test")
        menu.add_action("a", "A")
        menu.add_action("b", "B")
        self.assertEqual(len(menu.items), 2)
        menu.clear_items()
        self.assertEqual(len(menu.items), 0)
    
    def test_remove_item(self):
        """Test removing specific item."""
        menu = Menu("test")
        menu.add_action("a", "A")
        menu.add_action("b", "B")
        self.assertTrue(menu.remove_item("a"))
        self.assertEqual(len(menu.items), 1)
        self.assertIsNone(menu.get_item("a"))
    
    def test_remove_nonexistent_item(self):
        """Test removing non-existent item returns False."""
        menu = Menu("test")
        result = menu.remove_item("nonexistent")
        self.assertFalse(result)


class TestMenuValueManagement(unittest.TestCase):
    """Test menu value management."""
    
    def setUp(self):
        """Create test menu."""
        self.menu = Menu("test")
        self.menu.add_text_input("name", "Name", default="John")
        self.menu.add_numeric_input("age", "Age", default=25)
        self.menu.add_checkbox("agree", "Agree", default=False)
    
    def test_set_and_get_value(self):
        """Test setting and getting values."""
        self.menu.set_value("name", "Alice")
        self.assertEqual(self.menu.get_value("name"), "Alice")
    
    def test_set_nonexistent_value(self):
        """Test setting non-existent value returns False."""
        result = self.menu.set_value("nonexistent", "value")
        self.assertFalse(result)
    
    def test_get_nonexistent_value(self):
        """Test getting non-existent value returns None."""
        value = self.menu.get_value("nonexistent")
        self.assertIsNone(value)
    
    def test_get_all_values(self):
        """Test getting all values."""
        values = self.menu.get_all_values()
        self.assertEqual(values["name"], "John")
        self.assertEqual(values["age"], 25)
        self.assertEqual(values["agree"], False)
    
    def test_set_all_values(self):
        """Test setting multiple values."""
        new_values = {"name": "Bob", "age": 30, "agree": True}
        self.menu.set_all_values(new_values)
        self.assertEqual(self.menu.get_value("name"), "Bob")
        self.assertEqual(self.menu.get_value("age"), 30)
        self.assertEqual(self.menu.get_value("agree"), True)
    
    def test_reset_all(self):
        """Test resetting all values."""
        self.menu.set_value("name", "Changed")
        self.menu.set_value("age", 99)
        self.menu.reset_all()
        self.assertEqual(self.menu.get_value("name"), "John")
        self.assertEqual(self.menu.get_value("age"), 25)
    
    def test_numeric_validation_min(self):
        """Test numeric value validation (minimum)."""
        menu = Menu("test")
        menu.add_numeric_input("level", "Level", default=1, min_val=1, max_val=5)
        result = menu.set_value("level", -5)
        self.assertFalse(result)
        self.assertEqual(menu.get_value("level"), 1)  # Unchanged
    
    def test_numeric_validation_max(self):
        """Test numeric value validation (maximum)."""
        self.menu.add_numeric_input("level", "Level", default=1, min_val=1, max_val=5)
        result = self.menu.set_value("level", 10)
        self.assertFalse(result)
        self.assertEqual(self.menu.get_value("level"), 1)  # Unchanged


class TestMenuItemControl(unittest.TestCase):
    """Test item enable/disable and visibility control."""
    
    def setUp(self):
        """Create test menu."""
        self.menu = Menu("test")
        self.menu.add_action("a", "Action A")
        self.menu.add_action("b", "Action B")
        self.menu.add_action("c", "Action C")
    
    def test_disable_item(self):
        """Test disabling item."""
        self.assertTrue(self.menu.disable_item("a"))
        self.assertFalse(self.menu.get_item("a").enabled)
    
    def test_enable_item(self):
        """Test enabling item."""
        self.menu.get_item("a").enabled = False
        self.assertTrue(self.menu.enable_item("a"))
        self.assertTrue(self.menu.get_item("a").enabled)
    
    def test_hide_item(self):
        """Test hiding item."""
        self.assertTrue(self.menu.hide_item("a"))
        self.assertFalse(self.menu.get_item("a").visible)
    
    def test_show_item(self):
        """Test showing item."""
        self.menu.get_item("a").visible = False
        self.assertTrue(self.menu.show_item("a"))
        self.assertTrue(self.menu.get_item("a").visible)
    
    def test_get_visible_items(self):
        """Test getting only visible items."""
        self.menu.hide_item("a")
        visible = self.menu.get_visible_items()
        self.assertEqual(len(visible), 2)
        self.assertNotIn(self.menu.get_item("a"), visible)
    
    def test_get_enabled_items(self):
        """Test getting only enabled items."""
        self.menu.disable_item("a")
        enabled = self.menu.get_enabled_items()
        self.assertEqual(len(enabled), 2)
        self.assertNotIn(self.menu.get_item("a"), enabled)
    
    def test_disable_nonexistent_item(self):
        """Test disabling non-existent item returns False."""
        result = self.menu.disable_item("nonexistent")
        self.assertFalse(result)
    
    def test_enable_nonexistent_item(self):
        """Test enabling non-existent item returns False."""
        result = self.menu.enable_item("nonexistent")
        self.assertFalse(result)
    
    def test_hide_nonexistent_item(self):
        """Test hiding non-existent item returns False."""
        result = self.menu.hide_item("nonexistent")
        self.assertFalse(result)
    
    def test_show_nonexistent_item(self):
        """Test showing non-existent item returns False."""
        result = self.menu.show_item("nonexistent")
        self.assertFalse(result)


class TestSubmenus(unittest.TestCase):
    """Test submenu functionality."""
    
    def test_add_submenu(self):
        """Test adding submenu."""
        main = Menu("main")
        sub = Menu("sub", label="Submenu")
        item = main.add_submenu("sub_id", "Submenu Item", sub)
        
        self.assertIn("sub_id", main.items)
        self.assertIn("sub_id", main.submenus)
        self.assertEqual(item.item_type, ItemType.SUBMENU)
    
    def test_submenu_access(self):
        """Test accessing submenu."""
        main = Menu("main")
        sub = Menu("sub", label="Submenu")
        sub.add_action("action", "Action")
        main.add_submenu("sub_id", "Sub", sub)
        
        retrieved_sub = main.get_item("sub_id").submenu
        self.assertIsNotNone(retrieved_sub)
        self.assertIn("action", retrieved_sub.items)
    
    def test_nested_submenus(self):
        """Test nested submenus."""
        main = Menu("main")
        sub1 = Menu("sub1")
        sub2 = Menu("sub2")
        
        sub1.add_action("action", "Action")
        sub2.add_submenu("subsub", "Nested Sub", sub1)
        main.add_submenu("sub", "Sub", sub2)
        
        # Navigate nested
        sub2_retrieved = main.get_item("sub").submenu
        sub1_retrieved = sub2_retrieved.get_item("subsub").submenu
        self.assertIn("action", sub1_retrieved.items)
    
    def test_submenu_with_items(self):
        """Test submenu with multiple items."""
        main = Menu("main")
        settings = Menu("settings", label="Settings")
        
        settings.add_checkbox("sound", "Sound", default=True)
        settings.add_numeric_input("volume", "Volume", default=80, min_val=0, max_val=100)
        settings.add_radio("language", "Language", 
                          options=["English", "French"],
                          default="English")
        
        main.add_submenu("settings_id", "Settings", settings)
        
        retrieved = main.get_item("settings_id").submenu
        self.assertEqual(len(retrieved.items), 3)
    
    def test_submenu_value_independence(self):
        """Test that submenu values are independent."""
        main = Menu("main")
        main.add_text_input("name", "Name", default="Main")
        
        sub = Menu("sub")
        sub.add_text_input("name", "Name", default="Sub")
        
        main.add_submenu("sub_id", "Sub", sub)
        
        main.set_value("name", "Main Changed")
        sub.set_value("name", "Sub Changed")
        
        self.assertEqual(main.get_value("name"), "Main Changed")
        self.assertEqual(sub.get_value("name"), "Sub Changed")


class TestCallbacks(unittest.TestCase):
    """Test callback functionality."""
    
    def test_callback_on_action(self):
        """Test callback execution on action."""
        callback = Mock(return_value="Result")
        menu = Menu("test")
        menu.add_action("action", "Action", callback=callback)
        
        item = menu.get_item("action")
        result = item.execute()
        
        callback.assert_called_once()
        self.assertEqual(result, "Result")
    
    def test_callback_receives_item(self):
        """Test that callback receives the item."""
        callback = Mock()
        menu = Menu("test")
        menu.add_action("action", "Action", callback=callback)
        
        item = menu.get_item("action")
        item.execute()
        
        called_item = callback.call_args[0][0]
        self.assertEqual(called_item, item)
    
    def test_multiple_callbacks(self):
        """Test multiple items with callbacks."""
        cb1 = Mock(return_value="CB1")
        cb2 = Mock(return_value="CB2")
        
        menu = Menu("test")
        menu.add_action("a", "Action A", callback=cb1)
        menu.add_action("b", "Action B", callback=cb2)
        
        result1 = menu.get_item("a").execute()
        result2 = menu.get_item("b").execute()
        
        self.assertEqual(result1, "CB1")
        self.assertEqual(result2, "CB2")
        cb1.assert_called_once()
        cb2.assert_called_once()


class TestMenuCopy(unittest.TestCase):
    """Test menu copying functionality."""
    
    def test_copy_menu(self):
        """Test deep copying menu."""
        original = Menu("original")
        original.add_text_input("name", "Name", default="Original")
        original.add_action("action", "Action")
        
        copy = original.copy()
        
        self.assertEqual(copy.identifier, original.identifier)
        self.assertEqual(len(copy.items), len(original.items))
    
    def test_copy_independence(self):
        """Test that copy is independent from original."""
        original = Menu("original")
        original.add_text_input("name", "Name", default="Original")
        
        copy = original.copy()
        copy.set_value("name", "Copy Modified")
        original.set_value("name", "Original Modified")
        
        self.assertEqual(original.get_value("name"), "Original Modified")
        self.assertEqual(copy.get_value("name"), "Copy Modified")
    
    def test_copy_with_submenus(self):
        """Test copying menu with submenus."""
        original = Menu("original")
        sub = Menu("sub")
        sub.add_action("action", "Action")
        original.add_submenu("sub_id", "Sub", sub)
        
        copy = original.copy()
        copy_sub = copy.get_item("sub_id").submenu
        
        self.assertEqual(len(copy_sub.items), len(sub.items))
        self.assertIsNot(copy_sub, sub)


class TestFormValidation(unittest.TestCase):
    """Test form validation scenarios."""
    
    def test_registration_form(self):
        """Test registration form validation."""
        form = Menu("registration")
        form.add_text_input("email", "Email", default="")
        form.add_text_input("password", "Password", default="")
        form.add_numeric_input("age", "Age", default=18, min_val=13, max_val=120)
        form.add_checkbox("terms", "Agree to Terms", default=False)
        
        # Valid case
        form.set_value("email", "user@example.com")
        form.set_value("password", "secure123")
        form.set_value("age", 25)
        form.set_value("terms", True)
        
        values = form.get_all_values()
        self.assertEqual(values["email"], "user@example.com")
        self.assertEqual(values["password"], "secure123")
        self.assertEqual(values["age"], 25)
        self.assertTrue(values["terms"])
    
    def test_age_validation(self):
        """Test age validation."""
        form = Menu("form")
        form.add_numeric_input("age", "Age", default=18, min_val=13, max_val=120)
        
        # Valid
        self.assertTrue(form.set_value("age", 25))
        self.assertEqual(form.get_value("age"), 25)
        
        # Invalid - too young
        self.assertFalse(form.set_value("age", 10))
        self.assertEqual(form.get_value("age"), 25)  # Unchanged
        
        # Invalid - too old
        self.assertFalse(form.set_value("age", 150))
        self.assertEqual(form.get_value("age"), 25)  # Unchanged
    
    def test_profile_form(self):
        """Test profile form."""
        form = Menu("profile")
        form.add_text_input("username", "Username", default="")
        form.add_text_input("bio", "Bio", default="")
        form.add_radio("gender", "Gender",
                      options=["Male", "Female", "Other"],
                      default="Other")
        form.add_checkbox("public_profile", "Public Profile", default=False)
        
        form.set_all_values({
            "username": "john_doe",
            "bio": "Developer and gamer",
            "gender": "Male",
            "public_profile": True
        })
        
        values = form.get_all_values()
        self.assertEqual(values["username"], "john_doe")
        self.assertEqual(values["bio"], "Developer and gamer")
        self.assertEqual(values["gender"], "Male")
        self.assertTrue(values["public_profile"])


class TestEdgeCases(unittest.TestCase):
    """Test edge cases and error handling."""
    
    def test_empty_menu(self):
        """Test empty menu."""
        menu = Menu("empty")
        self.assertEqual(len(menu.items), 0)
        self.assertEqual(len(menu.get_visible_items()), 0)
        self.assertEqual(len(menu.get_enabled_items()), 0)
    
    def test_all_items_hidden(self):
        """Test menu with all items hidden."""
        menu = Menu("test")
        menu.add_action("a", "A")
        menu.add_action("b", "B")
        menu.hide_item("a")
        menu.hide_item("b")
        
        visible = menu.get_visible_items()
        self.assertEqual(len(visible), 0)
    
    def test_all_items_disabled(self):
        """Test menu with all items disabled."""
        menu = Menu("test")
        menu.add_action("a", "A")
        menu.add_action("b", "B")
        menu.disable_item("a")
        menu.disable_item("b")
        
        enabled = menu.get_enabled_items()
        self.assertEqual(len(enabled), 0)
    
    def test_empty_radio_options(self):
        """Test radio with empty options."""
        item = MenuItem("radio", "Radio", ItemType.RADIO, options=[])
        self.assertEqual(item.options, [])
    
    def test_separator_visibility(self):
        """Test separator in visible items list."""
        menu = Menu("test")
        menu.add_separator()
        menu.add_action("a", "A")
        
        # Separators are included in items but not usually in value management
        self.assertEqual(len(menu.items), 2)
        all_values = menu.get_all_values()
        self.assertEqual(len(all_values), 1)  # Only non-separator items
    
    def test_numeric_float_input(self):
        """Test numeric input with float."""
        menu = Menu("test")
        menu.add_numeric_input("price", "Price", default=9.99, min_val=0.0, max_val=999.99)
        
        menu.set_value("price", 19.99)
        self.assertEqual(menu.get_value("price"), 19.99)
        self.assertIsInstance(menu.get_value("price"), float)
    
    def test_very_long_label(self):
        """Test menu with very long label."""
        long_label = "A" * 1000
        item = MenuItem("long", long_label)
        self.assertEqual(len(item.label), 1000)
        self.assertEqual(item.label, long_label)
    
    def test_special_characters_in_label(self):
        """Test special characters in labels."""
        menu = Menu("test")
        menu.add_action("emoji", "👍 Like This")
        menu.add_action("special", "Item with \"quotes\" and 'apostrophes'")
        
        self.assertEqual(menu.get_item("emoji").label, "👍 Like This")
        self.assertIn("quotes", menu.get_item("special").label)
    
    def test_numeric_zero_value(self):
        """Test numeric item with zero value."""
        menu = Menu("test")
        menu.add_numeric_input("count", "Count", default=0, min_val=0, max_val=100)
        self.assertEqual(menu.get_value("count"), 0)
    
    def test_empty_text_value(self):
        """Test text item with empty value."""
        menu = Menu("test")
        menu.add_text_input("optional", "Optional", default="")
        self.assertEqual(menu.get_value("optional"), "")


class TestMenuSystem(unittest.TestCase):
    """Test MenuSystem class."""
    
    def test_create_menu_system(self):
        """Test creating MenuSystem."""
        system = MenuSystem()
        self.assertEqual(system.default_language, "en")
        self.assertEqual(system.current_language, "en")
    
    def test_create_menu_via_system(self):
        """Test creating menu via MenuSystem."""
        system = MenuSystem()
        menu = system.create_menu("main", label="Main Menu")
        
        self.assertIsNotNone(menu)
        self.assertEqual(menu.label, "Main Menu")
        self.assertIn("main", system.menus)
    
    def test_get_menu_from_system(self):
        """Test getting menu from MenuSystem."""
        system = MenuSystem()
        system.create_menu("main", label="Main")
        
        menu = system.get_menu("main")
        self.assertIsNotNone(menu)
        self.assertEqual(menu.label, "Main")
    
    def test_remove_menu_from_system(self):
        """Test removing menu from MenuSystem."""
        system = MenuSystem()
        system.create_menu("main", label="Main")
        
        self.assertTrue(system.remove_menu("main"))
        self.assertIsNone(system.get_menu("main"))
    
    def test_system_with_multiple_menus(self):
        """Test MenuSystem with multiple menus."""
        system = MenuSystem()
        system.create_menu("main", label="Main")
        system.create_menu("settings", label="Settings")
        system.create_menu("help", label="Help")
        
        self.assertEqual(len(system.menus), 3)
    
    def test_set_language(self):
        """Test setting language."""
        system = MenuSystem(default_language="en")
        self.assertEqual(system.current_language, "en")
        
        system.set_language("fr")
        self.assertEqual(system.current_language, "fr")
    
    def test_system_repr(self):
        """Test MenuSystem representation."""
        system = MenuSystem(default_language="fr")
        system.create_menu("main", label="Menu Principal")
        
        repr_str = repr(system)
        self.assertIn("MenuSystem", repr_str)
        self.assertIn("1", repr_str)


class TestRadioButtonItems(unittest.TestCase):
    """Test radio button specific functionality."""
    
    def test_radio_default_value(self):
        """Test radio with explicit default."""
        menu = Menu("test")
        options = ["Small", "Medium", "Large"]
        menu.add_radio("size", "Size", options=options, default="Medium")
        
        self.assertEqual(menu.get_value("size"), "Medium")
    
    def test_radio_auto_default(self):
        """Test radio with auto default (first option)."""
        menu = Menu("test")
        options = ["First", "Second", "Third"]
        menu.add_radio("choice", "Choice", options=options)
        
        self.assertEqual(menu.get_value("choice"), "First")
    
    def test_radio_change_value(self):
        """Test changing radio value."""
        menu = Menu("test")
        options = ["A", "B", "C"]
        menu.add_radio("option", "Option", options=options, default="A")
        
        menu.set_value("option", "B")
        self.assertEqual(menu.get_value("option"), "B")
    
    def test_radio_with_string_options(self):
        """Test radio with various string options."""
        menu = Menu("test")
        options = ["Python 3.6", "Python 3.8", "Python 3.10", "Python 3.11"]
        menu.add_radio("version", "Version", options=options, default="Python 3.10")
        
        self.assertEqual(menu.get_value("version"), "Python 3.10")
        menu.set_value("version", "Python 3.11")
        self.assertEqual(menu.get_value("version"), "Python 3.11")


class TestCheckboxItems(unittest.TestCase):
    """Test checkbox specific functionality."""
    
    def test_checkbox_toggle(self):
        """Test toggling checkbox."""
        menu = Menu("test")
        menu.add_checkbox("agree", "I Agree", default=False)
        
        self.assertFalse(menu.get_value("agree"))
        menu.set_value("agree", True)
        self.assertTrue(menu.get_value("agree"))
        menu.set_value("agree", False)
        self.assertFalse(menu.get_value("agree"))
    
    def test_multiple_checkboxes(self):
        """Test multiple independent checkboxes."""
        menu = Menu("test")
        menu.add_checkbox("a", "Option A", default=True)
        menu.add_checkbox("b", "Option B", default=False)
        menu.add_checkbox("c", "Option C", default=True)
        
        values = menu.get_all_values()
        self.assertTrue(values["a"])
        self.assertFalse(values["b"])
        self.assertTrue(values["c"])


class TestItemTypeEnum(unittest.TestCase):
    """Test ItemType enumeration."""
    
    def test_all_item_types(self):
        """Test all item type values."""
        types = [
            ItemType.TEXT,
            ItemType.NUMERIC,
            ItemType.CHECKBOX,
            ItemType.RADIO,
            ItemType.SUBMENU,
            ItemType.ACTION,
            ItemType.SEPARATOR
        ]
        self.assertEqual(len(types), 7)
    
    def test_item_type_values(self):
        """Test item type enum values."""
        self.assertEqual(ItemType.TEXT.value, "text")
        self.assertEqual(ItemType.NUMERIC.value, "numeric")
        self.assertEqual(ItemType.CHECKBOX.value, "checkbox")
        self.assertEqual(ItemType.RADIO.value, "radio")
        self.assertEqual(ItemType.SUBMENU.value, "submenu")
        self.assertEqual(ItemType.ACTION.value, "action")
        self.assertEqual(ItemType.SEPARATOR.value, "separator")


class TestComplexScenarios(unittest.TestCase):
    """Test complex real-world scenarios."""
    
    def test_game_configuration(self):
        """Test game configuration menu structure."""
        config = Menu("game_config", label="Game Configuration")
        
        # Graphics
        config.add_numeric_input("width", "Width", 
                                default=1920, min_val=800, max_val=3840)
        config.add_numeric_input("height", "Height", 
                                default=1080, min_val=600, max_val=2160)
        config.add_radio("quality", "Quality",
                        options=["Low", "Medium", "High", "Ultra"],
                        default="High")
        config.add_checkbox("fullscreen", "Fullscreen", default=False)
        config.add_checkbox("vsync", "V-Sync", default=True)
        
        # Audio
        config.add_numeric_input("master_volume", "Master Volume", 
                                default=80, min_val=0, max_val=100)
        config.add_numeric_input("music_volume", "Music Volume", 
                                default=70, min_val=0, max_val=100)
        config.add_checkbox("enable_effects", "Sound Effects", default=True)
        
        settings = config.get_all_values()
        # Note: get_all_values() only returns non-separator items
        self.assertEqual(len(settings), 8)
        self.assertEqual(settings["width"], 1920)
        self.assertEqual(settings["quality"], "High")
    
    def test_account_creation_wizard(self):
        """Test multi-step account creation."""
        step1 = Menu("step1", label="Personal Info")
        step1.add_text_input("first_name", "First Name")
        step1.add_text_input("last_name", "Last Name")
        step1.add_text_input("email", "Email")
        
        step2 = Menu("step2", label="Security")
        step2.add_text_input("password", "Password")
        step2.add_checkbox("two_factor", "Enable 2FA", default=False)
        
        step3 = Menu("step3", label="Preferences")
        step3.add_radio("language", "Language",
                       options=["English", "Français", "Español"],
                       default="English")
        step3.add_checkbox("newsletter", "Subscribe", default=True)
        
        # Fill all steps
        for menu in [step1, step2, step3]:
            for item in menu.items.values():
                if item.item_type == ItemType.TEXT:
                    menu.set_value(item.identifier, "test_value")
                elif item.item_type == ItemType.RADIO:
                    menu.set_value(item.identifier, item.options[0])
        
        # Verify
        self.assertEqual(len(step1.get_all_values()), 3)
        self.assertEqual(len(step2.get_all_values()), 2)
        self.assertEqual(len(step3.get_all_values()), 2)


class TestPerformance(unittest.TestCase):
    """Test performance with large menus."""
    
    def test_large_menu(self):
        """Test menu with many items."""
        menu = Menu("large")
        
        # Add 500 items
        for i in range(500):
            menu.add_action(f"item_{i}", f"Item {i}")
        
        self.assertEqual(len(menu.items), 500)
        self.assertIsNotNone(menu.get_item("item_250"))
    
    def test_many_submenus(self):
        """Test menu with many submenus."""
        main = Menu("main")
        
        # Add 100 submenus
        for i in range(100):
            sub = Menu(f"sub_{i}", label=f"Submenu {i}")
            sub.add_action("action", "Action")
            main.add_submenu(f"sub_id_{i}", f"Submenu {i}", sub)
        
        self.assertEqual(len(main.submenus), 100)
        self.assertEqual(len(main.items), 100)


def run_tests():
    """Run all tests."""
    unittest.main(argv=[''], exit=False, verbosity=2)


if __name__ == "__main__":
    run_tests()
