# Generated by AI - MultiTable Demo
"""Multi-dimensional table module demonstration."""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

from multitable import MultiTable

print("\nMulti-Dimensional Table - Interactive Demo")
print("=" * 60)

# Create a 2D table
table = MultiTable(2)
print(f"Created 2D table: {table}")

print("\nBasic Operations:")
print("1. Set values")
print("2. Get values")
print("3. Transpose")
print("\nSee multitable.py for full documentation")
