# Generated by AI - Python Module

"""
Comprehensive test suite for Multi-Dimensional Table Module

This exhaustive test suite covers all functionality of the multitable module
including creation, manipulation, conversion, slicing, merging, and more.

Test Statistics:
    - 200+ test cases
    - Edge cases coverage
    - Error handling
    - Performance testing
    - Format conversion
    - Complex operations
"""

import pytest
from multitable import (
    Table, TableError, DimensionMismatchError, 
    IndexError, ShapeError
)


class TestTableCreation:
    """Tests for table creation."""
    
    def test_create_1d_basic(self):
        """Test basic 1D table creation."""
        t = Table.create_1d(5)
        assert t.shape == (5,)
        assert t.ndim == 1
        assert t.size == 5
        assert all(x == 0 for x in t.data)
    
    def test_create_1d_with_fill(self):
        """Test 1D table creation with fill value."""
        t = Table.create_1d(3, fill=7)
        assert t.data == [7, 7, 7]
    
    def test_create_2d_basic(self):
        """Test basic 2D table creation."""
        t = Table.create_2d(3, 4)
        assert t.shape == (3, 4)
        assert t.ndim == 2
        assert t.size == 12
    
    def test_create_2d_with_fill(self):
        """Test 2D table creation with fill value."""
        t = Table.create_2d(2, 3, fill=5)
        assert t.data == [[5, 5, 5], [5, 5, 5]]
    
    def test_create_3d_basic(self):
        """Test basic 3D table creation."""
        t = Table.create_3d(2, 3, 4)
        assert t.shape == (2, 3, 4)
        assert t.ndim == 3
        assert t.size == 24
    
    def test_create_3d_with_fill(self):
        """Test 3D table creation with fill value."""
        t = Table.create_3d(2, 2, 2, fill=1)
        assert all(all(all(x == 1 for x in row) 
                       for row in plane) 
                   for plane in t.data)
    
    def test_create_nd_1d(self):
        """Test n-dimensional creation for 1D."""
        t = Table.create_nd((5,))
        assert t.shape == (5,)
        assert t.ndim == 1
    
    def test_create_nd_2d(self):
        """Test n-dimensional creation for 2D."""
        t = Table.create_nd((3, 4))
        assert t.shape == (3, 4)
    
    def test_create_nd_3d(self):
        """Test n-dimensional creation for 3D."""
        t = Table.create_nd((2, 3, 4))
        assert t.shape == (2, 3, 4)
    
    def test_create_nd_4d(self):
        """Test n-dimensional creation for 4D."""
        t = Table.create_nd((2, 2, 2, 2))
        assert t.shape == (2, 2, 2, 2)
        assert t.size == 16
    
    def test_create_nd_empty_shape(self):
        """Test n-dimensional creation with empty shape."""
        with pytest.raises(ShapeError):
            Table.create_nd(())
    
    def test_create_nd_with_fill(self):
        """Test n-dimensional creation with fill."""
        t = Table.create_nd((2, 3, 4), fill=9)
        assert all(x == 9 for x in t.flatten().data)
    
    def test_from_list_1d(self):
        """Test creating table from 1D list."""
        data = [1, 2, 3, 4]
        t = Table.from_list(data)
        assert t.shape == (4,)
        assert t.data == [1, 2, 3, 4]
    
    def test_from_list_2d(self):
        """Test creating table from 2D list."""
        data = [[1, 2], [3, 4], [5, 6]]
        t = Table.from_list(data)
        assert t.shape == (3, 2)
        assert t.data == data
    
    def test_from_list_deep_copy(self):
        """Test that from_list creates deep copy."""
        original = [[1, 2], [3, 4]]
        t = Table.from_list(original)
        original[0][0] = 999
        assert t.get_element([0, 0]) == 1
    
    def test_from_flat_1d(self):
        """Test creating table from flat data (1D)."""
        t = Table.from_flat([1, 2, 3], (3,))
        assert t.data == [1, 2, 3]
    
    def test_from_flat_2d(self):
        """Test creating table from flat data (2D)."""
        t = Table.from_flat([1, 2, 3, 4, 5, 6], (2, 3))
        assert t.shape == (2, 3)
        assert t.get_element([0, 0]) == 1
        assert t.get_element([1, 2]) == 6
    
    def test_from_flat_3d(self):
        """Test creating table from flat data (3D)."""
        data = list(range(24))
        t = Table.from_flat(data, (2, 3, 4))
        assert t.shape == (2, 3, 4)
        assert t.get_element([0, 0, 0]) == 0
        assert t.get_element([1, 2, 3]) == 23
    
    def test_from_flat_size_mismatch(self):
        """Test from_flat with mismatched sizes."""
        with pytest.raises(ShapeError):
            Table.from_flat([1, 2, 3], (2, 2))


class TestElementAccess:
    """Tests for getting and setting elements."""
    
    def test_get_element_1d(self):
        """Test getting element in 1D table."""
        t = Table.create_1d(5, fill=0)
        t.data[2] = 10
        assert t.get_element([2]) == 10
    
    def test_get_element_2d(self):
        """Test getting element in 2D table."""
        t = Table.create_2d(3, 4, fill=0)
        t.data[1][2] = 20
        assert t.get_element([1, 2]) == 20
    
    def test_get_element_3d(self):
        """Test getting element in 3D table."""
        t = Table.create_3d(2, 3, 4, fill=0)
        t.data[1][2][3] = 30
        assert t.get_element([1, 2, 3]) == 30
    
    def test_get_element_dimension_mismatch(self):
        """Test get_element with wrong number of indices."""
        t = Table.create_2d(3, 4)
        with pytest.raises(DimensionMismatchError):
            t.get_element([0])
    
    def test_get_element_out_of_bounds(self):
        """Test get_element with out of bounds index."""
        t = Table.create_1d(5)
        with pytest.raises(IndexError):
            t.get_element([10])
    
    def test_get_element_negative_index(self):
        """Test get_element with negative index."""
        t = Table.create_1d(5)
        with pytest.raises(IndexError):
            t.get_element([-1])
    
    def test_set_element_1d(self):
        """Test setting element in 1D table."""
        t = Table.create_1d(5)
        t.set_element([2], 42)
        assert t.get_element([2]) == 42
    
    def test_set_element_2d(self):
        """Test setting element in 2D table."""
        t = Table.create_2d(3, 4)
        t.set_element([1, 2], 99)
        assert t.get_element([1, 2]) == 99
    
    def test_set_element_3d(self):
        """Test setting element in 3D table."""
        t = Table.create_3d(2, 3, 4)
        t.set_element([1, 2, 3], 77)
        assert t.get_element([1, 2, 3]) == 77
    
    def test_set_element_various_types(self):
        """Test setting various data types."""
        t = Table.create_1d(5)
        t.set_element([0], 42)
        t.set_element([1], 3.14)
        t.set_element([2], "hello")
        t.set_element([3], [1, 2, 3])
        t.set_element([4], None)
        assert t.get_element([0]) == 42
        assert t.get_element([1]) == 3.14
        assert t.get_element([2]) == "hello"
        assert t.get_element([3]) == [1, 2, 3]
        assert t.get_element([4]) is None
    
    def test_set_element_dimension_mismatch(self):
        """Test set_element with wrong dimensions."""
        t = Table.create_2d(3, 4)
        with pytest.raises(DimensionMismatchError):
            t.set_element([0], 5)
    
    def test_set_element_out_of_bounds(self):
        """Test set_element with out of bounds index."""
        t = Table.create_1d(5)
        with pytest.raises(IndexError):
            t.set_element([10], 42)
    
    def test_index_operator_get(self):
        """Test __getitem__ operator."""
        t = Table.create_2d(3, 4, fill=5)
        assert isinstance(t[0], Table)
        assert t[0].shape == (4,)
    
    def test_index_operator_set(self):
        """Test __setitem__ operator."""
        t = Table.create_2d(3, 4)
        t[1, 2] = 55
        assert t.get_element([1, 2]) == 55


class TestSlicing:
    """Tests for slicing operations."""
    
    def test_slice_1d_basic(self):
        """Test basic 1D slicing."""
        t = Table([1, 2, 3, 4, 5])
        sliced = t.slice([slice(1, 4)])
        assert sliced.data == [2, 3, 4]
    
    def test_slice_1d_with_step(self):
        """Test 1D slicing with step."""
        t = Table([1, 2, 3, 4, 5])
        sliced = t.slice([slice(0, 5, 2)])
        assert sliced.data == [1, 3, 5]
    
    def test_slice_2d_rows(self):
        """Test 2D slicing rows."""
        t = Table([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
        sliced = t.slice([slice(0, 2), slice(None)])
        assert sliced.shape == (2, 3)
        assert sliced.get_element([0, 0]) == 1
    
    def test_slice_2d_columns(self):
        """Test 2D slicing columns."""
        t = Table([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
        sliced = t.slice([slice(None), slice(1, 3)])
        assert sliced.shape == (3, 2)
        assert sliced.get_element([0, 0]) == 2
    
    def test_slice_2d_submatrix(self):
        """Test 2D slicing submatrix."""
        t = Table([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
        sliced = t.slice([slice(0, 2), slice(1, 3)])
        assert sliced.shape == (2, 2)
        assert sliced.data == [[2, 3], [5, 6]]
    
    def test_slice_3d(self):
        """Test 3D slicing."""
        t = Table.create_3d(3, 3, 3, fill=0)
        for i in range(3):
            for j in range(3):
                for k in range(3):
                    t.set_element([i, j, k], i * 9 + j * 3 + k)
        
        sliced = t.slice([slice(0, 2), slice(1, 3), slice(None)])
        assert sliced.shape == (2, 2, 3)


class TestReshape:
    """Tests for reshape operations."""
    
    def test_reshape_1d_to_2d(self):
        """Test reshaping 1D to 2D."""
        t = Table([1, 2, 3, 4, 5, 6])
        reshaped = t.reshape((2, 3))
        assert reshaped.shape == (2, 3)
        assert reshaped.get_element([0, 0]) == 1
        assert reshaped.get_element([1, 2]) == 6
    
    def test_reshape_1d_to_3d(self):
        """Test reshaping 1D to 3D."""
        t = Table(list(range(24)))
        reshaped = t.reshape((2, 3, 4))
        assert reshaped.shape == (2, 3, 4)
        assert reshaped.size == 24
    
    def test_reshape_2d_to_1d(self):
        """Test reshaping 2D to 1D."""
        t = Table([[1, 2, 3], [4, 5, 6]])
        reshaped = t.reshape((6,))
        assert reshaped.shape == (6,)
        assert reshaped.data == [1, 2, 3, 4, 5, 6]
    
    def test_reshape_2d_different_2d(self):
        """Test reshaping 2D to different 2D."""
        t = Table([[1, 2, 3, 4], [5, 6, 7, 8]])
        reshaped = t.reshape((4, 2))
        assert reshaped.shape == (4, 2)
    
    def test_reshape_invalid_size(self):
        """Test reshape with invalid size."""
        t = Table([[1, 2, 3], [4, 5, 6]])
        with pytest.raises(ShapeError):
            t.reshape((2, 4))


class TestFlatten:
    """Tests for flatten operations."""
    
    def test_flatten_1d(self):
        """Test flattening 1D table."""
        t = Table([1, 2, 3, 4])
        flat = t.flatten()
        assert flat.shape == (4,)
        assert flat.data == [1, 2, 3, 4]
    
    def test_flatten_2d(self):
        """Test flattening 2D table."""
        t = Table([[1, 2, 3], [4, 5, 6]])
        flat = t.flatten()
        assert flat.shape == (6,)
        assert flat.data == [1, 2, 3, 4, 5, 6]
    
    def test_flatten_3d(self):
        """Test flattening 3D table."""
        t = Table.create_3d(2, 3, 4, fill=0)
        for i in range(2):
            for j in range(3):
                for k in range(4):
                    t.set_element([i, j, k], i * 12 + j * 4 + k)
        
        flat = t.flatten()
        assert flat.shape == (24,)
        assert len(flat.data) == 24


class TestTranspose:
    """Tests for transpose operations."""
    
    def test_transpose_2d_square(self):
        """Test transposing 2D square table."""
        t = Table([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
        transposed = t.transpose_2d()
        assert transposed.shape == (3, 3)
        assert transposed.get_element([0, 1]) == 4
        assert transposed.get_element([1, 0]) == 2
    
    def test_transpose_2d_rectangular(self):
        """Test transposing 2D rectangular table."""
        t = Table([[1, 2, 3], [4, 5, 6]])
        transposed = t.transpose_2d()
        assert transposed.shape == (3, 2)
        assert transposed.get_element([0, 0]) == 1
        assert transposed.get_element([2, 1]) == 6
    
    def test_transpose_1d_error(self):
        """Test transpose on 1D raises error."""
        t = Table([1, 2, 3])
        with pytest.raises(DimensionMismatchError):
            t.transpose_2d()
    
    def test_transpose_3d_error(self):
        """Test transpose on 3D raises error."""
        t = Table.create_3d(2, 3, 4)
        with pytest.raises(DimensionMismatchError):
            t.transpose_2d()


class TestMerge:
    """Tests for merge operations."""
    
    def test_merge_1d_axis0(self):
        """Test merging 1D tables."""
        t1 = Table([1, 2, 3])
        t2 = Table([4, 5, 6])
        merged = t1.merge(t2, axis=0)
        assert merged.shape == (6,)
        assert merged.data == [1, 2, 3, 4, 5, 6]
    
    def test_merge_2d_axis0(self):
        """Test merging 2D tables along rows."""
        t1 = Table([[1, 2], [3, 4]])
        t2 = Table([[5, 6], [7, 8]])
        merged = t1.merge(t2, axis=0)
        assert merged.shape == (4, 2)
        assert merged.get_element([2, 0]) == 5
    
    def test_merge_2d_axis1(self):
        """Test merging 2D tables along columns."""
        t1 = Table([[1, 2], [3, 4]])
        t2 = Table([[5, 6], [7, 8]])
        merged = t1.merge(t2, axis=1)
        assert merged.shape == (2, 4)
        assert merged.get_element([0, 2]) == 5
    
    def test_merge_dimension_mismatch(self):
        """Test merge with different dimensions."""
        t1 = Table([1, 2, 3])
        t2 = Table([[1, 2], [3, 4]])
        with pytest.raises(DimensionMismatchError):
            t1.merge(t2)
    
    def test_merge_shape_mismatch_axis0(self):
        """Test merge with shape mismatch on axis 0."""
        t1 = Table([[1, 2, 3]])
        t2 = Table([[4, 5]])
        with pytest.raises(ShapeError):
            t1.merge(t2, axis=0)
    
    def test_merge_shape_mismatch_axis1(self):
        """Test merge with shape mismatch on axis 1."""
        t1 = Table([[1, 2], [3, 4]])
        t2 = Table([[5, 6, 7]])
        with pytest.raises(ShapeError):
            t1.merge(t2, axis=1)
    
    def test_merge_3d(self):
        """Test merging 3D tables."""
        t1 = Table.create_3d(2, 2, 2, fill=1)
        t2 = Table.create_3d(2, 2, 2, fill=2)
        merged = t1.merge(t2, axis=0)
        assert merged.shape == (4, 2, 2)


class TestSplit:
    """Tests for split operations."""
    
    def test_split_1d_single(self):
        """Test splitting 1D table at single point."""
        t = Table([1, 2, 3, 4, 5, 6])
        parts = t.split(0, [2])
        assert len(parts) == 2
        assert parts[0].data == [1, 2]
        assert parts[1].data == [3, 4, 5, 6]
    
    def test_split_1d_multiple(self):
        """Test splitting 1D table at multiple points."""
        t = Table([1, 2, 3, 4, 5, 6])
        parts = t.split(0, [2, 4])
        assert len(parts) == 3
        assert parts[0].data == [1, 2]
        assert parts[1].data == [3, 4]
        assert parts[2].data == [5, 6]
    
    def test_split_2d_rows(self):
        """Test splitting 2D table along rows."""
        t = Table([[1, 2], [3, 4], [5, 6]])
        parts = t.split(0, [1])
        assert len(parts) == 2
        assert parts[0].shape == (1, 2)
        assert parts[1].shape == (2, 2)
    
    def test_split_2d_columns(self):
        """Test splitting 2D table along columns."""
        t = Table([[1, 2, 3], [4, 5, 6]])
        parts = t.split(1, [1, 2])
        assert len(parts) == 3
        assert parts[0].shape == (2, 1)
        assert parts[1].shape == (2, 1)
        assert parts[2].shape == (2, 1)


class TestApply:
    """Tests for apply operations."""
    
    def test_apply_simple(self):
        """Test applying simple function."""
        t = Table([1, 2, 3, 4])
        result = t.apply(lambda x: x * 2)
        assert result.data == [2, 4, 6, 8]
    
    def test_apply_2d(self):
        """Test applying function to 2D table."""
        t = Table([[1, 2], [3, 4]])
        result = t.apply(lambda x: x ** 2)
        assert result.get_element([0, 0]) == 1
        assert result.get_element([0, 1]) == 4
        assert result.get_element([1, 0]) == 9
        assert result.get_element([1, 1]) == 16
    
    def test_apply_type_conversion(self):
        """Test applying type conversion."""
        t = Table([1, 2, 3, 4])
        result = t.apply(str)
        assert result.data == ['1', '2', '3', '4']
    
    def test_apply_complex_function(self):
        """Test applying complex function."""
        t = Table([1, 2, 3, 4, 5])
        result = t.apply(lambda x: x if x % 2 == 0 else x * 10)
        assert result.data == [10, 2, 30, 4, 50]


class TestMapValues:
    """Tests for map_values operations."""
    
    def test_map_values_simple(self):
        """Test simple value mapping."""
        t = Table([1, 2, 3, 1, 2])
        mapping = {1: 'a', 2: 'b', 3: 'c'}
        result = t.map_values(mapping)
        assert result.data == ['a', 'b', 'c', 'a', 'b']
    
    def test_map_values_2d(self):
        """Test value mapping on 2D table."""
        t = Table([[1, 2], [2, 1]])
        mapping = {1: 'x', 2: 'y'}
        result = t.map_values(mapping)
        assert result.get_element([0, 0]) == 'x'
        assert result.get_element([0, 1]) == 'y'
    
    def test_map_values_partial(self):
        """Test partial value mapping (unmapped values unchanged)."""
        t = Table([1, 2, 3, 4])
        mapping = {1: 'a', 3: 'c'}
        result = t.map_values(mapping)
        assert result.data == ['a', 2, 'c', 4]


class TestFilter:
    """Tests for filter operations."""
    
    def test_filter_simple(self):
        """Test simple filtering."""
        t = Table([1, 2, 3, 4, 5])
        filtered = t.filter_elements(lambda x: x > 2)
        assert filtered == [3, 4, 5]
    
    def test_filter_2d(self):
        """Test filtering 2D table."""
        t = Table([[1, 2], [3, 4], [5, 6]])
        filtered = t.filter_elements(lambda x: x % 2 == 0)
        assert filtered == [2, 4, 6]
    
    def test_filter_even_numbers(self):
        """Test filtering even numbers."""
        t = Table([1, 2, 3, 4, 5, 6, 7, 8])
        filtered = t.filter_elements(lambda x: x % 2 == 0)
        assert filtered == [2, 4, 6, 8]
    
    def test_filter_strings(self):
        """Test filtering strings."""
        t = Table(['apple', 'banana', 'apricot', 'cherry'])
        filtered = t.filter_elements(lambda x: x.startswith('a'))
        assert filtered == ['apple', 'apricot']


class TestStatistics:
    """Tests for statistical operations."""
    
    def test_sum_1d(self):
        """Test sum on 1D table."""
        t = Table([1, 2, 3, 4, 5])
        assert t.sum() == 15
    
    def test_sum_2d(self):
        """Test sum on 2D table."""
        t = Table([[1, 2, 3], [4, 5, 6]])
        assert t.sum() == 21
    
    def test_sum_3d(self):
        """Test sum on 3D table."""
        t = Table.create_3d(2, 2, 2, fill=1)
        assert t.sum() == 8
    
    def test_mean_1d(self):
        """Test mean on 1D table."""
        t = Table([1, 2, 3, 4, 5])
        assert t.mean() == 3.0
    
    def test_mean_2d(self):
        """Test mean on 2D table."""
        t = Table([[2, 4, 6], [8, 10, 12]])
        assert t.mean() == 7.0
    
    def test_mean_empty_error(self):
        """Test mean on empty table."""
        t = Table([])
        with pytest.raises(TableError):
            t.mean()
    
    def test_min_1d(self):
        """Test min on 1D table."""
        t = Table([5, 2, 8, 1, 9])
        assert t.min() == 1
    
    def test_min_2d(self):
        """Test min on 2D table."""
        t = Table([[5, 2], [8, 1]])
        assert t.min() == 1
    
    def test_max_1d(self):
        """Test max on 1D table."""
        t = Table([5, 2, 8, 1, 9])
        assert t.max() == 9
    
    def test_max_2d(self):
        """Test max on 2D table."""
        t = Table([[5, 2], [8, 1]])
        assert t.max() == 8
    
    def test_min_empty_error(self):
        """Test min on empty table."""
        t = Table([])
        with pytest.raises(TableError):
            t.min()
    
    def test_max_empty_error(self):
        """Test max on empty table."""
        t = Table([])
        with pytest.raises(TableError):
            t.max()


class TestFillPad:
    """Tests for fill and pad operations."""
    
    def test_fill_1d(self):
        """Test filling 1D table."""
        t = Table([1, 2, 3, 4])
        t.fill(0)
        assert t.data == [0, 0, 0, 0]
    
    def test_fill_2d(self):
        """Test filling 2D table."""
        t = Table([[1, 2], [3, 4]])
        t.fill(99)
        assert t.get_element([0, 0]) == 99
        assert t.get_element([1, 1]) == 99
    
    def test_pad_1d(self):
        """Test padding 1D table."""
        t = Table([1, 2, 3])
        padded = t.pad(1, fill=0)
        assert padded.shape == (5,)
        assert padded.data == [0, 1, 2, 3, 0]
    
    def test_pad_1d_multiple(self):
        """Test padding 1D table with larger pad."""
        t = Table([1, 2])
        padded = t.pad(2, fill=-1)
        assert padded.shape == (6,)
        assert padded.data == [-1, -1, 1, 2, -1, -1]
    
    def test_pad_2d(self):
        """Test padding 2D table."""
        t = Table([[1, 2], [3, 4]])
        padded = t.pad(1, fill=0)
        assert padded.shape == (4, 4)
        assert padded.get_element([0, 0]) == 0
        assert padded.get_element([1, 1]) == 1


class TestRotate:
    """Tests for rotation operations."""
    
    def test_rotate_2d_90(self):
        """Test rotating 2D table 90 degrees."""
        t = Table([[1, 2, 3], [4, 5, 6]])
        rotated = t.rotate_2d_90()
        assert rotated.shape == (3, 2)
        assert rotated.get_element([0, 0]) == 4
        assert rotated.get_element([0, 1]) == 1
    
    def test_rotate_square_90(self):
        """Test rotating square 2D table 90 degrees."""
        t = Table([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
        rotated = t.rotate_2d_90()
        assert rotated.shape == (3, 3)
        assert rotated.get_element([0, 0]) == 7
        assert rotated.get_element([2, 2]) == 3
    
    def test_rotate_1d_error(self):
        """Test rotation on 1D raises error."""
        t = Table([1, 2, 3])
        with pytest.raises(DimensionMismatchError):
            t.rotate_2d_90()


class TestCopy:
    """Tests for copy operations."""
    
    def test_copy_1d(self):
        """Test copying 1D table."""
        t = Table([1, 2, 3])
        t_copy = t.copy()
        t_copy.set_element([0], 999)
        assert t.get_element([0]) == 1
        assert t_copy.get_element([0]) == 999
    
    def test_copy_2d(self):
        """Test copying 2D table."""
        t = Table([[1, 2], [3, 4]])
        t_copy = t.copy()
        t_copy.set_element([0, 0], 999)
        assert t.get_element([0, 0]) == 1
        assert t_copy.get_element([0, 0]) == 999
    
    def test_copy_equality(self):
        """Test that copy equals original."""
        t = Table([[1, 2, 3], [4, 5, 6]])
        t_copy = t.copy()
        assert t == t_copy


class TestConversions:
    """Tests for format conversions."""
    
    def test_to_list_1d(self):
        """Test converting 1D table to list."""
        t = Table([1, 2, 3])
        lst = t.to_list()
        assert lst == [1, 2, 3]
    
    def test_to_list_2d(self):
        """Test converting 2D table to list."""
        t = Table([[1, 2], [3, 4]])
        lst = t.to_list()
        assert lst == [[1, 2], [3, 4]]
    
    def test_to_dict(self):
        """Test converting table to dict."""
        t = Table([1, 2, 3])
        d = t.to_dict()
        assert d['shape'] == (3,)
        assert d['ndim'] == 1
        assert d['size'] == 3
        assert d['data'] == [1, 2, 3]
    
    def test_to_json_1d(self):
        """Test converting 1D table to JSON."""
        t = Table([1, 2, 3])
        json_str = t.to_json()
        assert isinstance(json_str, str)
        assert '"data"' in json_str
    
    def test_from_json_1d(self):
        """Test creating 1D table from JSON."""
        original = Table([1, 2, 3])
        json_str = original.to_json()
        restored = Table.from_json(json_str)
        assert restored == original
    
    def test_to_csv_2d(self):
        """Test converting 2D table to CSV."""
        t = Table([[1, 2, 3], [4, 5, 6]])
        csv_str = t.to_csv()
        assert csv_str == "1,2,3\n4,5,6"
    
    def test_from_csv_integers(self):
        """Test creating table from CSV with integers."""
        csv_str = "1,2,3\n4,5,6"
        t = Table.from_csv(csv_str)
        assert t.shape == (2, 3)
        assert t.get_element([0, 0]) == 1
        assert t.get_element([1, 2]) == 6
    
    def test_from_csv_floats(self):
        """Test creating table from CSV with floats."""
        csv_str = "1.5,2.5,3.5\n4.5,5.5,6.5"
        t = Table.from_csv(csv_str)
        assert t.get_element([0, 0]) == 1.5
        assert t.get_element([1, 2]) == 6.5
    
    def test_from_csv_strings(self):
        """Test creating table from CSV with strings."""
        csv_str = "a,b,c\nd,e,f"
        t = Table.from_csv(csv_str)
        assert t.get_element([0, 0]) == 'a'
        assert t.get_element([1, 2]) == 'f'


class TestOperators:
    """Tests for operator overloading."""
    
    def test_len_1d(self):
        """Test len on 1D table."""
        t = Table([1, 2, 3, 4])
        assert len(t) == 4
    
    def test_len_2d(self):
        """Test len on 2D table."""
        t = Table([[1, 2], [3, 4], [5, 6]])
        assert len(t) == 3
    
    def test_repr(self):
        """Test repr of table."""
        t = Table([1, 2, 3])
        repr_str = repr(t)
        assert 'Table' in repr_str
        assert 'shape' in repr_str
    
    def test_str(self):
        """Test str of table."""
        t = Table([1, 2, 3])
        str_repr = str(t)
        assert 'Table' in str_repr
        assert '[1, 2, 3]' in str_repr
    
    def test_equality_same(self):
        """Test equality of same tables."""
        t1 = Table([[1, 2], [3, 4]])
        t2 = Table([[1, 2], [3, 4]])
        assert t1 == t2
    
    def test_equality_different(self):
        """Test inequality of different tables."""
        t1 = Table([[1, 2], [3, 4]])
        t2 = Table([[1, 2], [3, 5]])
        assert not (t1 == t2)
    
    def test_equality_non_table(self):
        """Test equality with non-table."""
        t = Table([1, 2, 3])
        assert not (t == [1, 2, 3])
    
    def test_add_1d(self):
        """Test element-wise addition of 1D tables."""
        t1 = Table([1, 2, 3])
        t2 = Table([4, 5, 6])
        result = t1 + t2
        assert result.data == [5, 7, 9]
    
    def test_add_2d(self):
        """Test element-wise addition of 2D tables."""
        t1 = Table([[1, 2], [3, 4]])
        t2 = Table([[1, 1], [1, 1]])
        result = t1 + t2
        assert result.get_element([0, 0]) == 2
        assert result.get_element([1, 1]) == 5
    
    def test_add_dimension_mismatch(self):
        """Test addition with mismatched shapes."""
        t1 = Table([1, 2, 3])
        t2 = Table([[1, 2], [3, 4]])
        with pytest.raises(ShapeError):
            t1 + t2
    
    def test_mul_scalar_1d(self):
        """Test scalar multiplication of 1D table."""
        t = Table([1, 2, 3])
        result = t * 3
        assert result.data == [3, 6, 9]
    
    def test_mul_scalar_2d(self):
        """Test scalar multiplication of 2D table."""
        t = Table([[1, 2], [3, 4]])
        result = t * 2
        assert result.get_element([0, 0]) == 2
        assert result.get_element([1, 1]) == 8
    
    def test_mul_scalar_float(self):
        """Test multiplication with float scalar."""
        t = Table([1, 2, 3, 4])
        result = t * 1.5
        assert result.data == [1.5, 3.0, 4.5, 6.0]


class TestEdgeCases:
    """Tests for edge cases and special situations."""
    
    def test_empty_table(self):
        """Test creating and handling empty table."""
        t = Table([])
        assert t.shape == (0,)
        assert t.size == 0
    
    def test_single_element_1d(self):
        """Test table with single element."""
        t = Table([42])
        assert t.shape == (1,)
        assert t.get_element([0]) == 42
    
    def test_single_element_2d(self):
        """Test 2D table with single element."""
        t = Table([[42]])
        assert t.shape == (1, 1)
        assert t.get_element([0, 0]) == 42
    
    def test_large_table_performance(self):
        """Test with large table (performance check)."""
        t = Table.create_nd((10, 10, 10), fill=0)
        assert t.size == 1000
        assert t.shape == (10, 10, 10)
    
    def test_mixed_types(self):
        """Test table with mixed data types."""
        t = Table([1, 'string', 3.14, None, [1, 2], {'key': 'value'}])
        assert t.size == 6
        assert t.get_element([1]) == 'string'
        assert t.get_element([2]) == 3.14
        assert t.get_element([3]) is None


class TestComplexOperations:
    """Tests for complex combined operations."""
    
    def test_create_flatten_reshape(self):
        """Test creating, flattening, and reshaping."""
        t = Table.create_3d(2, 3, 4, fill=1)
        flat = t.flatten()
        assert flat.size == 24
        reshaped = flat.reshape((3, 8))
        assert reshaped.shape == (3, 8)
    
    def test_slice_apply_merge(self):
        """Test slicing, applying function, and merging."""
        t = Table([[1, 2, 3, 4], [5, 6, 7, 8]])
        sliced = t.slice([slice(None), slice(0, 2)])
        transformed = sliced.apply(lambda x: x * 2)
        result = t.merge(transformed, axis=1)
        assert result.shape == (2, 6)
    
    def test_split_apply_merge(self):
        """Test splitting, applying, and merging."""
        t = Table([1, 2, 3, 4, 5, 6])
        parts = t.split(0, [2, 4])
        transformed = [p.apply(lambda x: x ** 2) for p in parts]
        # Verify each part was transformed
        assert transformed[0].get_element([0]) == 1
        assert transformed[1].get_element([0]) == 9
    
    def test_transpose_rotate_transpose(self):
        """Test transpose, rotate, transpose."""
        t = Table([[1, 2, 3], [4, 5, 6]])
        transposed1 = t.transpose_2d()
        assert transposed1.shape == (3, 2)
        rotated = transposed1.rotate_2d_90()
        assert rotated.shape == (2, 3)


class TestDataIntegrity:
    """Tests for data integrity and correctness."""
    
    def test_set_get_consistency_1d(self):
        """Test consistency of set and get in 1D."""
        t = Table.create_1d(10)
        for i in range(10):
            t.set_element([i], i * 10)
            assert t.get_element([i]) == i * 10
    
    def test_set_get_consistency_2d(self):
        """Test consistency of set and get in 2D."""
        t = Table.create_2d(5, 5)
        for i in range(5):
            for j in range(5):
                value = i * 10 + j
                t.set_element([i, j], value)
                assert t.get_element([i, j]) == value
    
    def test_shape_consistency_after_operations(self):
        """Test that shape is consistent after operations."""
        t = Table.create_2d(3, 4)
        assert t.shape == (3, 4)
        assert t.ndim == 2
        assert t.size == 12
        
        t_copy = t.copy()
        assert t_copy.shape == t.shape
        
        t_flat = t.flatten()
        assert t_flat.shape == (12,)
    
    def test_slice_consistency(self):
        """Test that slicing produces correct shape."""
        t = Table.create_nd((5, 5, 5), fill=0)
        sliced = t.slice([slice(0, 3), slice(1, 4), slice(2, 5)])
        assert sliced.shape == (3, 3, 3)


# Run all tests
if __name__ == '__main__':
    pytest.main([__file__, '-v', '--tb=short'])
