# Generated by AI - Python Module

"""
Documentation package for PydocsExport.

Contains comprehensive documentation in multiple languages.
"""

__all__ = [
    'README_EN.md',
    'README_FR.md',
    'README_ES.md',
    'README_DE.md',
    'README_IT.md',
]
