# Generated by AI - Python Module

"""
PydocsExport - Python Documentation Export Module
==================================================

A comprehensive module for exporting Python documentation
in multiple formats: TXT, PDF, EPUB, MOBI, RTF, HTML,
XML, JSON, CSV, HLP, Markdown, reStructuredText, AZW,
DOCX, YAML, and SQLite.

Supported Features:
- Multiple export formats (16 total)
- PDF paper size support (A0-A10)
- Organized chapter structure with indexes
- Zero external dependencies

Quick Start:
    from PydocsExport import PydocsExporter

    exporter = PydocsExporter()
    results = exporter.export_all(['txt', 'md', 'json', 'sqlite'])

Author: PydocsExport Contributors
License: MIT
Version: 1.1.0
"""

__version__ = "1.1.0"
__author__ = "PydocsExport Contributors"
__license__ = "MIT"

from .src.exporter import PydocsExporter
from .src.formatter import (
    BaseFormatter,
    TextFormatter,
    PDFFormatter,
    EbookFormatter,
    RTFFormatter,
    XMLFormatter,
    JSONFormatter,
    CSVFormatter,
    HLPFormatter,
    MDFormatter,
    RSTFormatter,
    AZWFormatter,
    DOCXFormatter,
    YAMLFormatter,
    SQLiteFormatter,
)
from .src.index_manager import IndexManager

__all__ = [
    "PydocsExporter",
    "BaseFormatter",
    "TextFormatter",
    "PDFFormatter",
    "EbookFormatter",
    "RTFFormatter",
    "XMLFormatter",
    "JSONFormatter",
    "CSVFormatter",
    "HLPFormatter",
    "MDFormatter",
    "RSTFormatter",
    "AZWFormatter",
    "DOCXFormatter",
    "YAMLFormatter",
    "SQLiteFormatter",
    "IndexManager",
]
