# Generated by AI - Python Module

"""
This module was generated/enhanced by AI Assistant.
Provides professional-grade functionality with Python.
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Easy PydocsExport - Main Script
===============================

Export Python Documentation in Multiple Formats with One Command!

Description:
    This script allows users to easily export Python documentation
    to multiple formats: TXT, PDF, EPUB, MOBI, RTF, and HTML.

Usage:
    python EasyPydocsExport.py [options]

Options:
    --all              Export all formats (default)
    --txt              Export to TXT only
    --pdf              Export to PDF only (all paper sizes)
    --epub             Export to EPUB only
    --mobi             Export to MOBI only
    --rtf              Export to RTF only
    --html             Export to HTML only
    --format [fmt]     Specify format (can be repeated)
    --output [dir]     Output directory (default: pydocs_export_output)
    --help             Show this help message

Examples:
    python EasyPydocsExport.py
    python EasyPydocsExport.py --txt --pdf
    python EasyPydocsExport.py --output /custom/path
"""

import sys
import argparse
import os
from pathlib import Path
from datetime import datetime

# Import PydocsExport module
try:
    from src.exporter import PydocsExporter
except ImportError:
    print("[ERROR] Unable to import PydocsExporter module.")
    msg = "Make sure the 'src' package is available in the current directory."
    print(msg)
    sys.exit(1)


def print_banner():
    """Displays the welcome banner."""
    banner = """
+===================================================================+
|                                                                   |
|         EASY PYDOCS EXPORT - Documentation Exporter              |
|                                                                   |
|                        Version 1.0.0                             |
|                                                                   |
|       Export Python Documentation to Multiple Formats!            |
|                                                                   |
+===================================================================+
    """
    print(banner)


def parse_arguments():
    """Parses command-line arguments."""
    parser = argparse.ArgumentParser(
        description='Export Python documentation to multiple formats',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python EasyPydocsExport.py
  python EasyPydocsExport.py --txt --pdf
  python EasyPydocsExport.py --output /my/custom/path --all
        """
    )

    parser.add_argument(
        '--all',
        action='store_true',
        help='Export all formats (default if no format specified)'
    )

    parser.add_argument(
        '--txt',
        action='store_true',
        help='Export to TXT format'
    )

    parser.add_argument(
        '--pdf',
        action='store_true',
        help='Export to PDF format (all paper sizes)'
    )

    parser.add_argument(
        '--epub',
        action='store_true',
        help='Export to EPUB format'
    )

    parser.add_argument(
        '--mobi',
        action='store_true',
        help='Export to MOBI format'
    )

    parser.add_argument(
        '--rtf',
        action='store_true',
        help='Export to RTF format'
    )

    parser.add_argument(
        '--html',
        action='store_true',
        help='Export to HTML format'
    )

    parser.add_argument(
        '--xml',
        action='store_true',
        help='Export to XML format'
    )

    parser.add_argument(
        '--json',
        action='store_true',
        help='Export to JSON format'
    )

    parser.add_argument(
        '--csv',
        action='store_true',
        help='Export to CSV format'
    )

    parser.add_argument(
        '--hlp',
        action='store_true',
        help='Export to HLP (Windows Help) format'
    )

    parser.add_argument(
        '--md',
        action='store_true',
        help='Export to Markdown format'
    )

    parser.add_argument(
        '--rst',
        action='store_true',
        help='Export to reStructuredText format'
    )

    parser.add_argument(
        '--azw',
        action='store_true',
        help='Export to AZW (Amazon Kindle) format'
    )

    parser.add_argument(
        '--docx',
        action='store_true',
        help='Export to DOCX (Microsoft Word) format'
    )

    parser.add_argument(
        '--yaml',
        action='store_true',
        help='Export to YAML format'
    )

    parser.add_argument(
        '--sqlite',
        action='store_true',
        help='Export to SQLite database format'
    )

    parser.add_argument(
        '--format',
        action='append',
        dest='formats',
        help='Specify format (can be repeated)'
    )

    parser.add_argument(
        '--output',
        default='pydocs_export_output',
        help='Output directory (default: pydocs_export_output)'
    )

    return parser.parse_args()


def determine_formats(args):
    """Determines formats to export based on arguments."""
    formats = []

    # Check direct flags
    if args.txt:
        formats.append('txt')
    if args.pdf:
        formats.append('pdf')
    if args.epub:
        formats.append('epub')
    if args.mobi:
        formats.append('mobi')
    if args.rtf:
        formats.append('rtf')
    if args.html:
        formats.append('html')
    if args.xml:
        formats.append('xml')
    if args.json:
        formats.append('json')
    if args.csv:
        formats.append('csv')
    if args.hlp:
        formats.append('hlp')
    if args.md:
        formats.append('md')
    if args.rst:
        formats.append('rst')
    if args.azw:
        formats.append('azw')
    if args.docx:
        formats.append('docx')
    if args.yaml:
        formats.append('yaml')
    if args.sqlite:
        formats.append('sqlite')

    # Check --format option
    if args.formats:
        formats.extend(args.formats)

    # If --all or no format specified, export all
    if args.all or not formats:
        formats = ['txt', 'pdf', 'epub', 'mobi', 'rtf', 'html']

    # Remove duplicates and normalize
    formats = list(set(fmt.lower() for fmt in formats))

    return sorted(formats)


def validate_output_directory(output_dir):
    """Validates and creates the output directory if needed."""
    try:
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        return str(output_path.absolute())
    except Exception as e:
        print(f"[ERROR] Cannot create output directory: {e}")
        return None


def print_export_summary(results):
    """Displays export summary."""
    print("\n")
    print("+" + "=" * 78 + "+")
    print("|" + " EXPORT SUMMARY ".center(78) + "|")
    print("+" + "=" * 78 + "+")
    print()

    print(f"Timestamp: {results.get('timestamp', 'N/A')}")
    print(f"Total Modules: {results.get('total_modules', 0)}")
    print()

    print("Formats Exported:")
    print("-" * 80)
    for fmt, stats in results.get('formats', {}).items():
        if fmt.upper() == 'TXT':
            files = stats.get('files_created', 0)
            size = stats.get('total_size', 0)
            msg = f"  [OK] {fmt.upper():8} - {files:3d} files ({size:,} bytes)"
            print(msg)
        elif fmt.upper() == 'PDF':
            total = stats.get('total_files', 0)
            msg = f"  [OK] {fmt.upper():8} - {total} paper size files"
            print(msg)
        elif fmt.upper() == 'RTF':
            files = stats.get('files_created', 0)
            print(f"  [OK] {fmt.upper():8} - {files} files created")
        elif fmt.upper() == 'HTML':
            files = stats.get('files_created', 0)
            print(f"  [OK] {fmt.upper():8} - {files} files created")
        else:
            print(f"  [OK] {fmt.upper():8} - Exported")

    if results.get('errors'):
        print()
        print("Errors:")
        print("-" * 80)
        for error in results['errors']:
            print(f"  [WARNING] {error}")

    print()
    print("=" * 80)


def main():
    """Main entry point."""
    # Display banner
    print_banner()

    # Parse arguments
    args = parse_arguments()

    # Validate output directory
    output_dir = validate_output_directory(args.output)
    if not output_dir:
        sys.exit(1)

    print(f"[INFO] Output Directory: {output_dir}")
    print()

    # Determine formats to export
    formats = determine_formats(args)
    fmt_str = ', '.join(fmt.upper() for fmt in formats)
    print(f"[INFO] Formats to Export: {fmt_str}")
    print()

    # Create exporter
    print("[INIT] Initializing PydocsExporter...")
    exporter = PydocsExporter(output_base_dir=output_dir)

    # Export
    print("[START] Beginning export process...")
    print()

    try:
        results = exporter.export_all(formats=formats)

        # Display summary
        print_export_summary(results)

        print("[SUCCESS] Export completed successfully!")
        print(f"[INFO] All files saved to: {output_dir}")
        print()

        # Display output structure
        print("Output Structure:")
        print("-" * 80)
        dirs = [
            exporter.txt_dir,
            exporter.pdf_dir,
            exporter.epub_dir,
            exporter.mobi_dir,
            exporter.rtf_dir,
            exporter.html_dir,
        ]
        for d in dirs:
            rel_path = os.path.relpath(d, output_dir)
            if d.exists():
                file_count = len(list(d.glob('*.*')))
                print(f"  {rel_path}: {file_count} files")

        return 0

    except KeyboardInterrupt:
        print("\n\n[INTERRUPTED] Export interrupted by user.")
        return 1
    except Exception as e:
        print(f"\n\n[FATAL ERROR] {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    exit_code = main()
    sys.exit(exit_code)
