# Generated by AI - Python Module

"""
═════════════════════════════════════════════════════════════════════════════════
                        PYDOCSEXPORT - USAGE EXAMPLES
═════════════════════════════════════════════════════════════════════════════════

This file contains practical examples of how to use PydocsExport
in different scenarios.

Run any example with: python examples.py
═════════════════════════════════════════════════════════════════════════════════
"""

import sys
import os
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.exporter import PydocsExporter
from src.formatter import TextFormatter, PDFFormatter, EbookFormatter
from src.index_manager import IndexManager


def example_1_simple_export():
    """Example 1: Simple export to default location with all formats."""
    print("\n" + "=" * 80)
    print("EXAMPLE 1: Simple Export (All Formats)")
    print("=" * 80)
    
    exporter = PydocsExporter()
    results = exporter.export_all()
    
    print(f"\n✓ Exported {results['total_modules']} modules")
    print(f"✓ Formats: {list(results['formats'].keys())}")
    print(f"✓ Output directory: {exporter.output_base}")


def example_2_selective_export():
    """Example 2: Export only specific formats."""
    print("\n" + "=" * 80)
    print("EXAMPLE 2: Selective Export (TXT and HTML)")
    print("=" * 80)
    
    exporter = PydocsExporter(output_base_dir="example_output_2")
    results = exporter.export_all(formats=['txt', 'html'])
    
    print(f"\n✓ Exported formats: {list(results['formats'].keys())}")
    
    # Print file statistics
    for fmt, stats in results['formats'].items():
        print(f"✓ {fmt.upper()}: {stats}")


def example_3_custom_formatting():
    """Example 3: Using custom formatters."""
    print("\n" + "=" * 80)
    print("EXAMPLE 3: Custom Formatting")
    print("=" * 80)
    
    # Create a formatted document
    formatter = TextFormatter()
    
    # Add content
    formatter.add_title("Python Documentation Export", level=1)
    formatter.add_paragraph(
        "This is an example of how to use the TextFormatter "
        "to create nicely formatted documentation."
    )
    
    # Add code example
    formatter.add_code(
        """
def hello_world():
    print("Hello, Python World!")
    return True
        """,
        language="python"
    )
    
    # Get formatted content
    content = formatter.get_content()
    print("\n" + content)
    
    # Save to file
    output_file = Path("example_formatted_output.txt")
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(content)
    
    print(f"\n✓ Formatted content saved to: {output_file}")


def example_4_pdf_multiple_sizes():
    """Example 4: Exporting PDFs in multiple paper sizes."""
    print("\n" + "=" * 80)
    print("EXAMPLE 4: PDF with Multiple Paper Sizes")
    print("=" * 80)
    
    exporter = PydocsExporter(output_base_dir="example_output_4")
    results = exporter.export_all(formats=['pdf'])
    
    pdf_stats = results['formats']['pdf']
    
    print(f"\n✓ PDF files created for {len(pdf_stats['paper_sizes'])} paper sizes:")
    for size, info in pdf_stats['paper_sizes'].items():
        print(f"  - {size}: {info['file']}")


def example_5_index_management():
    """Example 5: Creating and managing indexes."""
    print("\n" + "=" * 80)
    print("EXAMPLE 5: Index Management")
    print("=" * 80)
    
    # Create index
    index = IndexManager()
    
    # Add entries
    modules = ['sys', 'os', 'json', 'pathlib', 'datetime', 'collections']
    for i, module in enumerate(modules, 1):
        index.add_entry(
            name=module,
            path=f"documentation/{module}.txt",
            category="built-in",
            file_size=1024 * (i * 10)
        )
    
    # Create index files in different formats
    output_dir = Path("example_output_5")
    output_dir.mkdir(exist_ok=True)
    
    # TXT format
    txt_index = index.create_index_file(output_dir, format="txt")
    print(f"\n✓ TXT Index created: {txt_index}")
    
    # JSON format
    json_index = index.create_index_file(output_dir, format="json")
    print(f"✓ JSON Index created: {json_index}")
    
    # HTML format
    html_index = index.create_index_file(output_dir, format="html")
    print(f"✓ HTML Index created: {html_index}")


def example_6_e_book_formatting():
    """Example 6: Creating e-book content."""
    print("\n" + "=" * 80)
    print("EXAMPLE 6: E-Book Formatting (EPUB/MOBI)")
    print("=" * 80)
    
    formatter = EbookFormatter()
    
    # Create an EPUB chapter
    epub_chapter = formatter.format_epub_chapter(
        "Chapter 1: Introduction",
        "This chapter introduces the basics of Python programming."
    )
    
    print("\n EPUB Chapter Example:")
    print(epub_chapter[:200] + "...")
    
    # Create MOBI chapter
    mobi_chapter = formatter.format_mobi_chapter(
        "Chapter 1: Introduction",
        "This chapter introduces the basics of Python programming."
    )
    
    print("\n MOBI Chapter Example:")
    print(mobi_chapter[:200] + "...")
    
    # Create TOC XML
    chapters = [
        {'title': 'Introduction', 'file': 'intro.html'},
        {'title': 'Getting Started', 'file': 'getting_started.html'},
        {'title': 'Advanced Topics', 'file': 'advanced.html'},
    ]
    
    toc_xml = formatter.create_toc_xml(chapters)
    print("\n TOC XML created with " + str(len(chapters)) + " chapters")


def example_7_programmatic_workflow():
    """Example 7: Complete programmatic workflow."""
    print("\n" + "=" * 80)
    print("EXAMPLE 7: Complete Programmatic Workflow")
    print("=" * 80)
    
    # Step 1: Initialize exporter
    print("\n[STEP 1] Initializing exporter...")
    exporter = PydocsExporter(output_base_dir="example_output_7")
    
    # Step 2: Get list of modules
    print("[STEP 2] Retrieving module list...")
    modules = exporter._get_all_modules()
    print(f"  → Found {len(modules)} modules")
    
    # Step 3: Create custom index
    print("[STEP 3] Creating custom index...")
    index = IndexManager()
    for module in modules[:10]:  # First 10 modules
        index.add_entry(module, f"modules/{module}", "python-built-in", 1024)
    
    # Step 4: Export formats
    print("[STEP 4] Exporting to formats...")
    results = exporter.export_all(formats=['txt', 'html'])
    
    # Step 5: Generate reports
    print("[STEP 5] Generating reports...")
    print(f"\n  Export Summary:")
    print(f"  - Timestamp: {results['timestamp']}")
    print(f"  - Total Modules: {results['total_modules']}")
    print(f"  - Formats Exported: {len(results['formats'])}")
    print(f"  - Errors: {len(results['errors'])}")


def example_8_error_handling():
    """Example 8: Error handling and robustness."""
    print("\n" + "=" * 80)
    print("EXAMPLE 8: Error Handling")
    print("=" * 80)
    
    try:
        # Try to export
        exporter = PydocsExporter(output_base_dir="example_output_8")
        
        # Handle potential errors
        results = exporter.export_all(formats=['txt', 'pdf'])
        
        if results['errors']:
            print(f"\n⚠ {len(results['errors'])} error(s) encountered:")
            for error in results['errors']:
                print(f"  - {error}")
        else:
            print("\n✓ Export completed without errors")
            
    except Exception as e:
        print(f"\n✗ Error during export: {e}")
        import traceback
        traceback.print_exc()


def main():
    """Run all examples."""
    print("""
╔════════════════════════════════════════════════════════════════════════════════╗
║                                                                                ║
║                      PYDOCSEXPORT - PRACTICAL EXAMPLES                         ║
║                                                                                ║
║  This script demonstrates various ways to use the PydocsExport module.        ║
║                                                                                ║
╚════════════════════════════════════════════════════════════════════════════════╝
    """)
    
    examples = [
        example_1_simple_export,
        example_2_selective_export,
        example_3_custom_formatting,
        example_4_pdf_multiple_sizes,
        example_5_index_management,
        example_6_e_book_formatting,
        example_7_programmatic_workflow,
        example_8_error_handling,
    ]
    
    for i, example in enumerate(examples, 1):
        try:
            example()
        except Exception as e:
            print(f"\n✗ Example {i} failed: {e}")
            import traceback
            traceback.print_exc()
    
    print("\n" + "=" * 80)
    print("ALL EXAMPLES COMPLETED")
    print("=" * 80)
    print("\nFor more information, see:")
    print("  - README.md (Main documentation)")
    print("  - QUICKSTART.md (Quick start guide)")
    print("  - docs/ (Full documentation in multiple languages)")
    print()


if __name__ == "__main__":
    main()
