# Generated by AI - Python Module

"""
PydocsExport Main Module - Simple API
=====================================

This module provides a convenient interface for using
PydocsExport as an imported module.

Example Usage:
    from PydocsExport import quick_export

    # Export in all formats
    results = quick_export()

    # Export in specific formats
    results = quick_export(['txt', 'html', 'pdf'])

    # Export to custom directory
    results = quick_export(['txt'], output_dir='my_docs')
"""

from src.exporter import PydocsExporter
from typing import List, Optional, Dict


def quick_export(
    formats: Optional[List[str]] = None,
    output_dir: str = "pydocs_export_output"
) -> Dict:
    """
    Quick export function for Python documentation.

    Args:
        formats: List of export formats. Supported formats:
                ['txt', 'pdf', 'epub', 'mobi', 'rtf', 'html',
                 'xml', 'json', 'csv', 'hlp', 'md', 'rst', 'azw',
                 'docx', 'yaml', 'sqlite'].
                If None, exports in all formats.
        output_dir: Base output directory for exports.

    Returns:
        Dictionary with export statistics and results.

    Example:
        >>> results = quick_export(['txt', 'html'])
        >>> print(f"Exported {results['total_modules']} modules")
    """
    if formats is None:
        formats = ['txt', 'pdf', 'epub', 'mobi', 'rtf', 'html',
                   'xml', 'json', 'csv', 'hlp', 'md', 'rst', 'azw',
                   'docx', 'yaml', 'sqlite']

    print("PydocsExport v1.1.0")
    print(f"Exporting to: {output_dir}")
    print(f"Formats: {', '.join(formats)}\n")

    exporter = PydocsExporter(output_base_dir=output_dir)
    results = exporter.export_all(formats)

    return results


def export_txt(output_dir: str = "pydocs_export_output") -> Dict:
    """
    Export documentation as TXT format only.

    Args:
        output_dir: Output directory for exports.

    Returns:
        Export results dictionary.
    """
    exporter = PydocsExporter(output_base_dir=output_dir)
    return exporter.export_all(['txt'])


def export_pdf(output_dir: str = "pydocs_export_output") -> Dict:
    """
    Export documentation as PDF format only.

    Args:
        output_dir: Output directory for exports.

    Returns:
        Export results dictionary.
    """
    exporter = PydocsExporter(output_base_dir=output_dir)
    return exporter.export_all(['pdf'])


def export_ebooks(output_dir: str = "pydocs_export_output") -> Dict:
    """
    Export documentation as e-book formats (EPUB, MOBI, RTF).

    Args:
        output_dir: Output directory for exports.

    Returns:
        Export results dictionary.
    """
    exporter = PydocsExporter(output_base_dir=output_dir)
    return exporter.export_all(['epub', 'mobi', 'rtf'])


def export_html(output_dir: str = "pydocs_export_output") -> Dict:
    """
    Export documentation as HTML format only.

    Args:
        output_dir: Output directory for exports.

    Returns:
        Export results dictionary.
    """
    exporter = PydocsExporter(output_base_dir=output_dir)
    return exporter.export_all(['html'])


def export_structured(output_dir: str = "pydocs_export_output") -> Dict:
    """
    Export documentation in structured formats (XML, JSON, CSV).

    Args:
        output_dir: Output directory for exports.

    Returns:
        Export results dictionary.
    """
    exporter = PydocsExporter(output_base_dir=output_dir)
    return exporter.export_all(['xml', 'json', 'csv'])


def export_all_formats(
    output_dir: str = "pydocs_export_output"
) -> Dict:
    """
    Export documentation in all supported formats.

    This is equivalent to quick_export() with no parameters.

    Args:
        output_dir: Output directory for exports.

    Returns:
        Export results dictionary.
    """
    exporter = PydocsExporter(output_base_dir=output_dir)
    all_formats = ['txt', 'pdf', 'epub', 'mobi', 'rtf', 'html',
                   'xml', 'json', 'csv', 'hlp', 'md', 'rst', 'azw',
                   'docx', 'yaml', 'sqlite']
    return exporter.export_all(all_formats)


def export_markdown(output_dir: str = "pydocs_export_output") -> Dict:
    """Export documentation in Markdown format."""
    exporter = PydocsExporter(output_base_dir=output_dir)
    return exporter.export_all(['md'])


def export_rst_format(output_dir: str = "pydocs_export_output") -> Dict:
    """Export documentation in reStructuredText format."""
    exporter = PydocsExporter(output_base_dir=output_dir)
    return exporter.export_all(['rst'])


def export_ebook_formats(output_dir: str = "pydocs_export_output") -> Dict:
    """Export documentation in all ebook formats (EPUB, MOBI, AZW)."""
    exporter = PydocsExporter(output_base_dir=output_dir)
    return exporter.export_all(['epub', 'mobi', 'azw'])


def export_office_formats(output_dir: str = "pydocs_export_output") -> Dict:
    """Export documentation in office formats (DOCX, PDF)."""
    exporter = PydocsExporter(output_base_dir=output_dir)
    return exporter.export_all(['docx', 'pdf'])


def export_data_formats(output_dir: str = "pydocs_export_output") -> Dict:
    """Export documentation in data formats (XML, JSON, YAML, SQLite)."""
    exporter = PydocsExporter(output_base_dir=output_dir)
    return exporter.export_all(['xml', 'json', 'yaml', 'sqlite'])


if __name__ == "__main__":
    """
    Main entry point when run as a script.
    Exports all formats to default output directory.
    """
    print("=" * 70)
    print("PydocsExport - Python Documentation Export Tool")
    print("=" * 70)
    print()

    results = quick_export()

    print()
    print("=" * 70)
    print("Export Summary")
    print("=" * 70)
    print(f"Total modules exported: {results.get('total_modules', 'N/A')}")
    print(f"Formats completed: {len(results.get('formats', {}))}")
    if results.get('errors'):
        print(f"Errors encountered: {len(results['errors'])}")
    else:
        print("No errors!")
    print()
    print("Check the 'pydocs_export_output' directory for results.")
