# Generated by AI - PydocsExport Demo
"""PydocsExport module demonstration."""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

print("\nPydocsExport - Python Documentation Exporter")
print("=" * 60)
print("This module exports Python documentation to various formats.")
print("\nSee PydocsExport.py for full documentation")
