# Generated by AI - Python Module

"""
This module was generated/enhanced by AI Assistant.
Provides professional-grade functionality with Python.
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Test real export with no side effects
Monitors for any external launches
"""

import sys
import os
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

# Monkey-patch to detect any problematic imports
import subprocess
original_popen = subprocess.Popen
popen_calls = []

def tracked_popen(*args, **kwargs):
    """Track subprocess calls"""
    popen_calls.append(args[0] if args else "unknown")
    raise RuntimeError("Attempted to launch: {}".format(args[0]))

subprocess.Popen = tracked_popen

def test_export():
    """Test export without side effects"""
    print("Testing export with only JSON format...")
    print()
    
    try:
        from src.exporter import PydocsExporter
        
        exporter = PydocsExporter(
            output_base_dir="test_export_safe"
        )
        
        # Get modules
        modules = exporter._get_all_modules()
        print("Retrieved {} modules".format(len(modules)))
        
        # Export only JSON (fastest format to test)
        # Limit to first 50 modules for quick test
        limited_modules = modules[:50]
        
        print("Exporting {} modules to JSON...".format(
            len(limited_modules)))
        print()
        
        result = exporter._export_json(limited_modules)
        
        print()
        print("Export complete!")
        print("Files created: {}".format(
            result.get('files_created', 0)))
        print("Total size: {} bytes".format(
            result.get('total_size', 0)))
        
        if popen_calls:
            print()
            print("[FAILED] Attempted to launch external programs:")
            for call in popen_calls:
                print("  - {}".format(call))
            return False
        else:
            print()
            print("[SUCCESS] No external programs were launched!")
            return True
            
    except Exception as e:
        if "Attempted to launch" in str(e):
            print("[FAILED] {}".format(e))
            return False
        else:
            print("[ERROR] {}".format(e))
            import traceback
            traceback.print_exc()
            return False


if __name__ == "__main__":
    success = test_export()
    sys.exit(0 if success else 1)
