# Generated by AI - Python Module

"""
This module was generated/enhanced by AI Assistant.
Provides professional-grade functionality with Python.
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Test progress display for PydocsExporter
"""

import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent))

from src.exporter import PydocsExporter

def test_progress_display():
    """Test the progress display with percentage."""
    print("Testing progress display...")
    print()
    
    # Create a test exporter
    output_dir = Path("test_output")
    exporter = PydocsExporter(output_base_dir=str(output_dir))
    
    # Test _format_progress method directly
    print("Testing _format_progress() method:")
    print("-" * 60)
    
    test_cases = [
        (1, 10),
        (5, 10),
        (10, 10),
        (50, 200),
        (100, 200),
        (200, 200),
        (1, 100),
        (25, 100),
        (50, 100),
        (75, 100),
        (100, 100),
    ]
    
    for current, total in test_cases:
        progress = exporter._format_progress(current, total)
        print(f"  {progress}")
    
    print()
    print("Testing module filtering in _get_all_modules():")
    print("-" * 60)
    
    # Get all modules and display some statistics
    modules = exporter._get_all_modules()
    print(f"Total modules found: {len(modules)}")
    print()
    
    # Check for any suspicious entries
    suspicious = []
    for module in modules:
        if module.startswith("http://") or module.startswith("https://"):
            suspicious.append(f"  ✗ URL found: {module}")
        elif "/" in module or "\\" in module:
            suspicious.append(f"  ✗ Path found: {module}")
        elif module.endswith(".html"):
            suspicious.append(f"  ✗ HTML file found: {module}")
    
    if suspicious:
        print("Found suspicious entries:")
        for item in suspicious:
            print(item)
    else:
        print("✓ No external URLs, paths, or HTML files found in module list")
    
    print()
    print("Sample modules (first 10):")
    for i, module in enumerate(modules[:10], 1):
        print(f"  {i:2d}. {module}")
    
    print()
    print("✓ Progress display test completed successfully!")

if __name__ == "__main__":
    test_progress_display()
