# Generated by AI - Python Module

"""
This module was generated/enhanced by AI Assistant.
Provides professional-grade functionality with Python.
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Test that no external programs or websites are launched during export
"""

import sys
import subprocess
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent))

def test_no_side_effects():
    """Test that exporting doesn't launch external programs."""
    print("Testing for external program launches...")
    print()
    
    try:
        from src.exporter import PydocsExporter
        exporter = PydocsExporter(output_base_dir="test_no_side_effects")
        
        # Get modules (should not trigger any side effects)
        modules = exporter._get_all_modules()
        print("[OK] Successfully retrieved {} modules".format(len(modules)))
        
        # Test format_progress (should not require any external deps)
        progress = exporter._format_progress(50, 100)
        print("[OK] Progress formatting works")
        
        # Test getting help for a module (should NOT import it)
        help_text = exporter._get_module_full_help("os")
        print("[OK] Got help for 'os' module ({} chars)".format(len(help_text)))
        
        # Test with a potentially problematic module
        help_text = exporter._get_module_full_help("json")
        print("[OK] Got help for 'json' module ({} chars)".format(len(help_text)))
        
        # Test with other modules
        help_text = exporter._get_module_full_help("sys")
        print("[OK] Got help for 'sys' module ({} chars)".format(len(help_text)))
        
        print()
        print("[SUCCESS] No external programs were launched!")
        return True
        
    except Exception as e:
        print("[ERROR] {}".format(e))
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    success = test_no_side_effects()
    sys.exit(0 if success else 1)
